### PR TITLE
 	Change icons with GNOME logo for icons with MATE logo

### PR DESCRIPTION
**Pull request by darkshram**

### CODE REVIEW

**Comment by infirit** [comment]
Viewing this on github, the new 32x32 mate-panel.png is a fair bit smaller than the old one. Is that done intentionally? Also the 32x32 svg seems to have shifted down and thus is missing the bottom.

The 48x48 icons look good :+1:

**Comment by darkshram** [comment]
No, they are not done intentionally. The 32x32 icons I made are wrong. I'll correct them in a few minutes.

**Comment by darkshram** [comment]
The 32x32 icon is a completle different icon from de 48x48. My mistake was to asume the 32x32 was just a resized version on the 48x48. So I left the rest to rsvg-convert. I'll commit the corrected icons in a few minutes.

**Comment by darkshram** [comment]
Done. These ones look Ok.

**Comment by infirit** [comment]
They do, merged squashed with a slightly modified commit message in e7bf6c58a687f047ca570f53840a862898f2832a.

Thx

**Pull request closed without merging**
