### PR TITLE
Gtk-WARNING: Allocating size to GtkAlignment..

### PR DESCRIPTION
**Pull request by dnk**
https://github.com/mate-desktop/mate-panel/issues/359

### CODE REVIEW

**Comment by lukefromdc** [comment]
I just tested this, it suppressed these two warnings out of the total set and did not prevent the image on the button menu from reloading on theme change(as I figured it might):
```

Jan  8 14:05:57 ubuntu trashapplet[16103]: Allocating size to GtkImage 0x56027582d140 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Jan  8 14:05:57 ubuntu trashapplet[16103]: Allocating size to GtkImage 0x56027582d140 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to to allocate?
```

**Comment by dnk** [comment]
I have https://github.com/dnk/mate-panel/commit/ee2e01de69f9a8be83b580ac436393307c64ca89

**Comment by lukefromdc** [comment]
I just tested https://github.com/dnk/mate-panel/commit/ee2e01de69f9a8be83b580ac436393307c64ca89 by itself (applied by hand to master), it suppressed this pair of warnings only:

Jan  9 17:21:52 ubuntu mate-cpufreq-ap[4858]: gtk_orientable_get_orientation: assertion 'GTK_IS_ORIENTABLE (orientable)' failed
Jan  9 17:21:52 ubuntu mate-cpufreq-ap[4858]: gtk_orientable_get_orientation: assertion 'GTK_IS_ORIENTABLE (orientable)' failed

**Comment by lukefromdc** [comment]
I just tested this PR with GTK 3.22, 3.20, 3.18, and 3.16 and everything worked in all of them. I will merge this and then start a dev-warnings branch to work on some of the other warnings

**Comment by lukefromdc** [comment]
I am now getting exactly the same warnings as before, but the removed code seemed to have no effect, indicating it is useless code and should be removed anyway.

**Comment by monsta** [comment]
Oops, looks like it should've been removed along with comment above it when removing GTK+2 code [here](https://github.com/mate-desktop/mate-panel/commit/d0ddaedffa7d417a699cafce73c1e418515c4a28#diff-91454453959d3a3d2ea52621511e4ae5L246). Thanks, I will adjust code in 1.16 branch as well.

**Pull request merged**
