### PR TITLE
Fixes #549

### LINKED ISSUE #549: Some GTK settings breaks Applications Places System menu bar.
To reproduce:
add to ~/.config/gtk-3.0/settings.ini
```
[Settings]
gtk-shell-shows-app-menu=true
gtk-shell-shows-menubar=true
```

Result:
Menu bar disappeared.
Expected result:
Menu bar stays in place.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/43739276-some-gtk-settings-breaks-applications-places-system-menu-bar?utm_campaign=plugin&utm_content=tracker%2F314880&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F314880&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by rilian-la-te**

### CODE REVIEW

**Comment by lukefromdc** [comment]
Not sure what to do with this, as I was unable to duplicate the issue

**Comment by raveit65** [comment]
We should wait until we really understand what the issue is.

**Comment by alexarnaud** [comment]
Le 04/04/2017 à 09:00, raveit65 a écrit :
> We should wait until we really understand what the issue is.

It's understandable to the user perspective : to create a new keyboard 
shortcut at the moment we need to know the exact path of the application 
binary and to understand correctly the concept of a folders hierarchy.

With this patch the user has only to choose the application from a list, 
it becomes in my opinion really user-friendly to add a new keyboard 
shortcut for an application.

Best regards.
-- 
Alex ARNAUD
Visual-Impairment Project Manager
Hypra - "Humanizing technology"

**Comment by raveit65** [comment]
@alexarnaud 
Are you sure you posted to right PR?

**Comment by cwendling** [comment]
@alexarnaud @raveit65 nah, I think he meant to comment on https://github.com/mate-desktop/mate-control-center/pull/274 ;)

**Comment by raveit65** [comment]
@flexiondotorg 
Is this PR in 17.04 for testing?

**Comment by flexiondotorg** [comment]
No yet.

**Comment by lukefromdc** [comment]
Merged with https://github.com/mate-desktop/mate-panel/commit/be71ad60d8b05fe0b4f8ac409122ee905a1a4e28

**Comment by raveit65** [comment]
@lukefromdc @rilian-la-te 
Can you please edit commit header next time?
'git format-patch commit-id' gives this weird patch name which say nothing.
0001-Fixes-549.patch

...and it looks bad in git log...
Thank you

**Comment by rilian-la-te** [comment]
Yes. But I does not know how to call commits (If you look to vala-panel-appmenu, you will see this weird names). Can you help me?

**Comment by raveit65** [comment]
'git rebase -i' (interactive), its easy to use. But we can't do this here after merging as a 'pull-f' after rebase can break every local repo.

**Comment by raveit65** [comment]
err, i meant push -f

**Comment by rilian-la-te** [comment]
I asking not about git commands, but about commit name conventions. How to do it, and how to name useless and almost useless commits?

**Comment by raveit65** [comment]
A commit header should shorty describe what the commit does, ie. 'panel-applet: port GtkTable to GtkGrid' or in thgis case
'panel-menu-bar: read GtkSettings values'
or something like this, 
But using a number to a report works only on a website.

**Comment by rilian-la-te** [comment]
But what about useless commits, like formatting modification or generic fixes?

**Comment by monsta** [comment]
Here's a recent example of minor commit: https://github.com/mate-desktop/mate-panel/commit/de0611f1b7d937ce8c316ab8643349875aa80cc5

**Comment by lukefromdc** [comment]
I didn't even catch that, was too focussed on results and didn't pay enough attention to the comment

**Comment by lukefromdc** [comment]
It's possible if needed to make a branch holding this commit, revert it in master, edit the header in the branch, and merge it again. Better comment at the price of more noise in the changelog.

**Pull request closed without merging**
