### PR TITLE
Revert "window-list: remove intermediate steps to get scaled thumbnail"

### PR DESCRIPTION
**Pull request by vkareh**
This reverts commit 08146a80fc1727cde7a6d02d8436f2c86c159b8c.

This commit breaks the thumbnail refreshing, causing the thumbnail to be always stuck in the first generated image of a window, rather than following its changes. Reverting it fixes it so that the thumbnail is always captured on the latest state of the window.

### CODE REVIEW

**Comment by rbuj** [comment]
Without this pr the thumbnail is refreshed if the window is resized, therefore there is some way to force new thumbnail when necessary.

**Comment by lukefromdc** [comment]
I can confirm the issue here

**Review by lukefromdc — APPROVED** [review]
Builds and runs fine, and I can confirm both that thumbnails are NOT updated on master at this point, and that they are updated again and work as expected with the PR

**Comment by rbuj** [comment]
#1190 may be related to the issue about updating thumbnails

**Comment by vkareh** [comment]
Fixed by #1190

**Pull request closed without merging**
