### PR TITLE
Remove unnecessary cast in g_signal_connect* call

### PR DESCRIPTION
**Pull request by rbuj**
In addition, use dashes for signals: applet-added, applet-removed, applet-move, back-change, size-change

### CODE REVIEW

**Review by lukefromdc — APPROVED** [review]
Builds and runs fine, I checked changing several preferences to check that signals work, notably changing timezones from the calendar by changing locations. Note that when changing time zones to test signals the time itself has to update in order for the change to be reflected in the clock applet, same as with master. If you set the time preferences to display seconds this change will be displayed almost immediately as displaying seconds forces an update every second. Same behavior as in master

**Comment by raveit65** [comment]
@rbuj  
Can you please do a push to get an deployment for travis?

**Comment by rbuj** [comment]
@raveit65 done

**Comment by raveit65** [comment]
@rbuj 
Ohh, looks like we have conflict after merging last PRs.

**Comment by rbuj** [comment]
@raveit65 done. In addition, use dashes for signals: applet-added, applet-removed, applet-move, back-change, size-change.

**Review by raveit65 — APPROVED** [review]
LGTM,
applet runs fine.

**Pull request merged**
