### PR TITLE
Backport memory leak fixes and critical bug fixes from gnome-panel

### PR DESCRIPTION
**Pull request by rcaridade145**
Hello.
This pull request backports two bugfixes made to gnome-panel.

### CODE REVIEW

**Comment by raveit65** [comment]
Gnome-panel has the same build warning.

**Comment by raveit65** [comment]
const PangoFontDescription *font_desc;   -->  PangoFontDescription *font_desc;  silence the warnung.
But i don't know if that makes sense.

**Comment by raveit65** [comment]
rebased and merged
https://github.com/mate-desktop/mate-panel/commit/2e35407bfe71cf0c9c5911102daf8ed2e7246d89
https://github.com/mate-desktop/mate-panel/commit/4c30c52e4857da9d23e284aa75b12c8ab62e2ee4
Thank you

**Comment by thexavier666** [comment]
@raveit65 
Hi, I'm still facing the issue. 50% memory usage in an 8 GB machine after leaving it running for 2-3 days.
I am on Mate version 1.20.1

I'm not sure but is it the case that I've not received the update?
Note: I update using the standard `sudo apt update && sudo apt upgrade`

**Comment by raveit65** [comment]
> Note: I update using the standard sudo apt update && sudo apt upgrade

You need to ask your distro maintainer for that. I am living in RPM land (redhat/fedora)

**Comment by lukefromdc** [comment]
I don't see these commits on any 1.20 release, 1.20.3 is the most recent and is now in Debian Unstable but these two commits are only present in Master as of Sep 18 2018.

**Comment by raveit65** [comment]
Feel free to back port them to 1.20 as it is a bugfix, but i don't do a new release only for 2 commits.

**Comment by lukefromdc** [comment]
I tried a quick cherrypick to 1.20 of these two commits, but it did not work because something in it referenced the mate-menus changes between 1.20 and master and caused build failures. Got these errors:

panel-run-dialog.c:769:2: error: unknown type name ‘MateMenuTreeItem’; did you mean ‘MateMenuTreeIter’?
  MateMenuTreeItem *aliased_item;


panel-run-dialog.c:834:35: error: ‘MATEMENU_TREE_SORT_DISPLAY_NAME’ undeclared (first use in this function); did you mean ‘MATEMENU_TREE_FLAGS_SORT_DISPLAY_NAME’?
  matemenu_tree_set_sort_key(tree, MATEMENU_TREE_SORT_DISPLAY_NAME);

**Comment by raveit65** [comment]
For testing building mate-panel-1.20 branch you need to downgrade to mate-menus-1.20.1.
But don't restart your session with that version, because mate-panel from master won't start any more.  
Did the cherry-pick command itself work?

**Comment by lukefromdc** [comment]
The cherrypick itself did work, no problems at all there

**Comment by lukefromdc** [comment]
OK, 1.20.3 plus these two commits cherrypicked builds and runs fine with mate-menus 1.20. Will push shortly

**Comment by lukefromdc** [comment]
Cherrypicked to 1.20, done

**Pull request closed without merging**
