### PR TITLE
avoid deprecated 'g_type_class_add_private'

### PR DESCRIPTION
**Pull request by sc0w**

### CODE REVIEW

**Comment by lukefromdc** [comment]
I have nm-applet built with indicator support and started with` nm-applet --indicator` so I'm thinking something in how that uses the status notifier (I see /org/ayatana/NotificationItem/nm_applet in the backtrace) would be why I got the segfault and the previous tester did not.

**Comment by sc0w** [comment]
@lukefromdc I am working now with this PR installed and it seems to work fine. How to reproduce the crash step by step?

**Comment by lukefromdc** [comment]
Open the calendar, expand it to include the map/locations/clock faces, click
"edit," then try to add a location. When you have one selected, try to add it, that's
when the crash occurs on my box(I am not at it right now). If this does not occue on
your system you probably cannot duplicate it.

Note that when the panel restarts the location has been sucessfully added, so the
crash must be in the final portion of that code(os as I suspect in something called
by it).

**Comment by sc0w** [comment]
@lukefromdc seems you are mentioned the issue https://github.com/mate-desktop/mate-panel/issues/1017 not related to this PR (I can't reproduce the problem)

**Comment by lukefromdc** [comment]
Oh yeah, that's it-and I just confirmed it again with master, so it is not related to this PR. When I previously tested it, I must have gotten a successful close of the dialog without a crash by chance, as this happens most but not quite all of the time. Sorry for the noise on that, it means this PR should be ready to go as we never had a problem with this code change before, I didn't get any other issues, and the issue I did get is now confirmed (again) to exist on master too. Approving

**Comment by lukefromdc** [comment]
Shit: I got totally confused this morning and asked you to try to duplicate the WRONG issue, which is common to master. Was away from my desktop and there had been much conversation about that other issue.

**Comment by lukefromdc** [comment]
I also just tested reverting the changes to applets/notification_area/status-notifier/sn-item.c and keeping the rest of this, and the resulting build worked and didn't crash on bringing back nm-applet in indicator mode.

**Comment by lukefromdc** [comment]
Playing with the file I found that the first change adding 
`G_ADD_PRIVATE (SnItem)` does not crash the panel on running `nm-applet --indicator` if I am right (I don't really know a lot about this) this should support both the old and the new way of handling this.

Then replacing `item->priv = G_TYPE_INSTANCE_GET_PRIVATE (item, SN_TYPE_ITEM, SnItemPrivate);` with item->priv = sn_item_get_instance_private (item) brings about the crash.
`
item->priv = sn_item_get_instance_private (item)` is used elsewhere in the code before this PR but seems not to work for sn_item_init, maybe it's not ready in time?

**Comment by sc0w** [comment]
not here, I did:

```
$ killall nm-applet
$ nm-applet --indicator
```

and mate-panel doesn't crash, I need to do additional steps?

**Comment by lukefromdc** [comment]
OK,that means you will might be able to duplicate the crash. Maybe you have a build
of nm-applet that does not support indicator mide? Its a build-time option and not all
distros use it. In that case, try any known status notifier, I will try our own mate-polkit 
with it enabled (my normal build) tonight. If you still cannot duplicate it I will be out of
ideas except for.trying to fix it myself.

**Comment by lukefromdc** [comment]
The issue seems to be on any indicator. I just tried mate-polkit built with sni support, and on mounting an internal partition from caja, the panel crashed and went into another restart/crash loop(from the session manager respawning it as usual) as soon as mate-polkit tried to display the keys icon as an indicator.

**Comment by lukefromdc** [comment]
I tested modifying sn_item_init to put a message in terminal if item->priv comes up null
```
static void
sn_item_init (SnItem *item)
{
  item->priv = sn_item_get_instance_private (item);
  if (item->priv == NULL)
      g_message("invalid item->priv");

  gtk_widget_add_events (GTK_WIDGET (item), GDK_SCROLL_MASK);
}
```
and with this got `notification-area-applet-Message: 00:28:30.881: invalid item->priv` just before the segfault, indicating that ` item->priv = sn_item_get_instance_private (item);` in `sn_item_init` is not working here.

**Comment by sc0w** [comment]
I think the problem is this line in `sn-item.c`:

`#define sn_item_get_instance_private(i) (SN_ITEM (i)->priv)`

@lukefromdc I did new changes, please test again

**Pull request merged**
