### PR TITLE
Replace wayland-scanner private-code option with code

### PR DESCRIPTION
**Pull request by wmww**
Should fix the problem noted here: https://github.com/mate-desktop/mate-panel/pull/899#issuecomment-447844869

### CODE REVIEW

**Comment by wmww** [comment]
The problem is that apparently on Debian stable, the `wayland-scanner` is too old to support the `private-code` option. Replacing it with just `code` is deprecated, but works fine for now. This PR has nothing to do with the `--enable-*` flags.

**Comment by raveit65** [comment]
Do we really should support old debian stable for wayland support?
Debian stable will never be updated to next mate-1.22.
For the record, debian stable use mate-1.18 which is EOL.
I am in doubt that someone will test experimental wayland support for mate-panel on deprecated debian-stable.
So why introducing deprecated code?

**Comment by raveit65** [comment]
And i am in doubt that Ubuntu 18.04 will ever been update to next mate-1.22 or a future version with mate-panel for wayland. Maybe ubuntu maintainer have a plan to update LTS version.
@flexiondotorg  ^^^^^^

Your decision, if you think it is useful to support older distro releases without mate-panel for wayland, i will follow you.

To be realistic, i don't think that a working wayland session for Mate is ready before mate-1.24/26

**Comment by wmww** [comment]
It doesn't matter if someone wants to get a Wayland session running on Ubuntu 18.04 or not. This is just to fix the build system so it doesn't crap out on those distros when not given an explicit `--enable-x11`. Even if it won't be used much, there's no reason I see to go to extra trouble to disallow building with Wayland on the latest Ubuntu LTS.

**Comment by raveit65** [comment]
Should be tested with debian-stable or ubuntu-18.04 installed.
Sorry, i don't use those distros.

**Comment by wmww** [comment]
I've tested on Ubuntu 18.04, and @monsta [has tested](https://github.com/mate-desktop/mate-panel/pull/899#issuecomment-448579890) on Debian stable.

**Comment by wmww** [comment]
I fixed the issue of `make clean` not removing generated code, and I made some adjustments to the build options.

As before, both backends are built by default, but now explicitly enabling one does not disable the other. Rather, they're both set to `auto` by default, which will cause them to build if available, but not cause an error otherwise. If the `--enable-*` flag is passed for either, it causes an error if the libraries are not found, and if `--disable-*` it causes that backend to not be built.

**Comment by raveit65** [comment]
> I've tested on Ubuntu 18.04, and @monsta has tested on Debian stable.

and @monsta  is part of core-team and is privilege to merge PR

**Comment by lukefromdc** [comment]
As expected, passing --disable-x11 yields

`configure: error: No support yet for non-X11 builds`

**Pull request merged**
