### PR TITLE
fix make distcheck fail on debian

### PR DESCRIPTION
**Pull request by yetist**
Please review and test it.

### CODE REVIEW

**Comment by lukefromdc** [comment]
Fixed on Debian-but Travis says failed on Arch Linux, didn't see that when I posted my review. This fixes Debian, I don't know if Arch was also broken in master or not though, and I don't have an Arch install to test on nor the bandwidth to download a new installer

**Comment by yetist** [comment]
archlinux maybe OK at #927, first merge #928, then #927, all will be OK.

**Comment by raveit65** [comment]
https://github.com/mate-desktop/mate-panel/pull/927 is merged and i did a
`git rebase master && git push -f` on this branch.
Should build fine now for all distros at travis.

**Comment by raveit65** [comment]
I will cherry-pick that to 1.20 branch to get travis-CI working on that branch too.

**Comment by yetist** [comment]
@raveit65 

Maybe the pot file should be updated, please don't forget to do that.

**Comment by raveit65** [comment]
Thanks, i will do

**Comment by raveit65** [comment]
done https://github.com/mate-desktop/mate-panel/commit/6471edf7abaded482f3d01e223a4fef37742e645

**Pull request merged**
