### PR TITLE
fix some deprecations

### PR DESCRIPTION
**Pull request by raveit65**
I hope i did not break anything :)
Most stuff is gtk3 only but a few commits affect gtk2 too.
@monsta @lukefromdc 
Can you please test it?

### CODE REVIEW

**Comment by lukefromdc** [comment]
I just built this  in gtk3.19, everything works. I noticed the "edit" button in the opened up calendar with the world map showing is now on the far right side of the calendar rather than next to the "Locations" expander, which could confuse someone.

Also, in running the panel from terminal I still get GtkWidget:focus-line-width and  GtkWidget:focus-padding showing up as deprecated style properties loading from data.  Changing themes does not change this, further verifying this to be still loading from data somewhere. Terminal gets spammed with these, making other work from terminal (as in background experiments) difficult

**Comment by raveit65** [comment]
> Also, in running the panel from terminal I still get GtkWidget:focus-line-width and GtkWidget:focus-padding showing up as deprecated style properties loading from data. 

This comes from an applet somewhere, maybe from mate-applets. For the applets from mate-panel i've removed those deprecated styles properties, ie. with 
https://github.com/mate-desktop/mate-panel/commit/0828507731be133f03703ac6403959f74e897f34
We need to remove this also from mate-applets.

**Comment by raveit65** [comment]
Btw. caja have some deprecated properties too.

**Comment by lukefromdc** [comment]
I just tested applets by removing them and adding them back, the window-list is the source of the remaining focus-line-width  and focus-padding style properties . No other applet in my setup did this, though the clock always gets 

`(mate-panel:4970): GLib-GObject-WARNING **: /build/glib2.0-2.46.2/./gobject/gsignal.c:2516: signal 'size_request' is invalid for instance '0x1bbe300' of type 'GtkLabel'`

MOVING an applet sometimes gets a 

`(mate-panel:3978): Gtk-WARNING **: Allocating size to GtkAlignment 0x280d2a0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?`

This also sometimes pops up on first adding an applet that takes a lot of space like hardware sensors or workspace switcher, probably because of something having to move.

**Comment by lukefromdc** [comment]
Just tested the window list after building the panel with the lines focus-line-width  and focus-padding physically removed from every last instance in the code-and they STILL came up when running with the window list in the panel from terminal. This means it must be coming in with something loaded by the window list applet, but it only appears in "colorsel" in mate-desktop.   Tried compiz, marco, and even gtk2 based IceWM in case it was coming in from the window manager itself, no difference.

**Comment by raveit65** [comment]
Let us open a new report to work on this warnings because they are not related to this PR.
Best way to find the 'focus-line-width' or other deprecated properties is to 'grep' on a tarball.
I guess for the other warning we need to run mate-panel or other mate apps with 'export G_DEBUG=fatal-criticals' in 'gdb' to find out at which place in the code a  gtk_widget_get_preferred_width/height() is expected.

**Comment by raveit65** [comment]
@monsta 
i updated
do not use deprecated gdk_cursor_new
add missing 'static' to avoid a build warning

Anything left?

**Comment by raveit65** [comment]
@monsta 
Maybe you find some time to fix this deprecated warning?
```
panel-profile.c:1700:2: Warnung: »gdk_display_get_n_screens« ist veraltet [-Wdeprecated-declarations]
  n_screens = gdk_display_get_n_screens (display);
  ^
In file included from /usr/include/gtk-3.0/gdk/gdkscreen.h:32:0,
                 from /usr/include/gtk-3.0/gdk/gdkapplaunchcontext.h:31,
                 from /usr/include/gtk-3.0/gdk/gdk.h:32,
                 from panel-profile.h:29,
                 from panel-profile.c:28:
/usr/include/gtk-3.0/gdk/gdkdisplay.h:52:13: Anmerkung: hier deklariert
 gint        gdk_display_get_n_screens      (GdkDisplay  *display);
             ^
```
I tried it for myself but no luck.
You can take a look at 'GTK+3: do not use deprecated n_screens', to see how it goes.

**Comment by monsta** [comment]
> I noticed the "edit" button in the opened up calendar with the world map showing is now on the far right side of the calendar rather than next to the "Locations" expander, which could confuse someone.

Well it's so in GTK+2:

calendar

I think it looks alright...

**Comment by lukefromdc** [comment]
Good enough

**Comment by raveit65** [comment]
merged

**Pull request closed without merging**
