### PR TITLE
limit size of panel-hide-button

### PR DESCRIPTION
**Pull request by raveit65**
fix for https://github.com/mate-desktop/mate-panel/issues/786

### CODE REVIEW

**Comment by raveit65** [comment]
> ....should we address that too?

If you want to address this than open another report which can be fix by another PR.

**Comment by info-cppsp** [comment]
Please don't get this exited, just because a random user reports something.
My PR works for the majority of users.
Please try to think of mate as a complex system and try not to add features just because someone asks for it. As far as I am concerned this isn't a bloatware factory.

Apart from that, I see the problem with the use case.
Let me think about it.
Share your ideas.

Hardcoding something that works, is still just hardcoding. - Which is bad...
What if the next guy comes along and says that the button should be even smaller?
Or bigger / wider, because it looks stupid like this?
What if someone likes squares, even if they are 150*150px ?

**Comment by raveit65** [comment]
Why should someone wants a squared button of 150x150px?

**Comment by raveit65** [comment]
I just updated PR.
- same size of buttons with or without using the arrow
- much more simplify
- size values are updated for both arrow and button to match more previous behaviour before the square button was commited.

@monsta @lukefromdc 
Please test again.

**Comment by monsta** [comment]
> same size of buttons with or without using the arrow

Not exactly, but I just pushed a small adjustment for large panel size :slightly_smiling_face:

**Comment by monsta** [comment]
Looks ok, it's now close to behavior before https://github.com/mate-desktop/mate-panel/commit/fa5cde36593be06eabfb2f752f38c26b80ea269c.

**Comment by monsta** [comment]
Interesting, before https://github.com/mate-desktop/mate-panel/commit/fa5cde36593be06eabfb2f752f38c26b80ea269c toplevel had `arrow-size` property which was supposed to define arrow size. But that property was only read in two places, nobody ever set it, except for the initial (default) value. :slightly_smiling_face: 

```
#define DEFAULT_ARROW_SIZE        20
```
Actually, the property is still there, just not used anymore at all.

**Comment by raveit65** [comment]
Hmm, for me the button looks to big with using
> 40 = 26
> 60 = 30
with a HIDIPI monitor.
But i don't really care as i use auto-hide panel in favor of this button ;)

**Comment by lukefromdc** [comment]
Works fine on a retest, and gives same size hide buttons with or without the arrow shown. Yes, if I set window-scaling=2 they render wider, remembering that on a real HiDIP display the close pixel spacing would presumably narrow that back down again

**Comment by raveit65** [comment]
Ok, than HIDIPI users needs to live with it. I will squash commits.

**Comment by raveit65** [comment]
@monsta Is this ready to go and you want approve the PR?

**Comment by monsta** [comment]
Sorry, I didn't think about HiDPI (as usual). Is the button much bigger now? It should be just a few more pixels, and as @lukefromdc mentioned, it should be less visible difference on a real HiDPI monitor.

From my side, this looks good to go.

**Comment by raveit65** [comment]
@monsta 
vert-panel with 70px (your values)
vert-panel-70px-to-large     previous version  vert-panel-70px

well, not a real problem for me, but it looks to huge for my taste.

**Comment by lukefromdc** [comment]
If we shrink the hide buttons for the hidpi case and don't use a selector switch, they will become tiny when the arrows (which should force a minimum size) are not shown on a non-hidpi monitor. Don't judge by the ballooned appearance of testing window-scaling=2 on a small monitor like what I have.

**Comment by raveit65** [comment]
Can someone post a screenshot how a 70px vert. panel looks with buttons and this PR, please?

**Comment by lukefromdc** [comment]
Here are some screenshots, I used GtkInspector to change the theme to Adwaita-Dark to put borders on the buttons, and to quickly toggle the window scaling. Some icon names on the desktop are redacted.

70px, window-
left_panel_24px2_adwaita_dark
scaling=1
left_panel_70px_adwaita_dark
70px., window-scaling=2
left_panel_24px2_adwaita_dark

24px, window-scaling=2

**Comment by raveit65** [comment]
any way, i will leave it like it is.

**Pull request merged**
