### PR TITLE
Enable clang-analyzer

### PR DESCRIPTION
**Pull request by yetist**

### CODE REVIEW

**Comment by yetist** [comment]
Clang Analyzer results of aff11f022ed980385051c6acf60d4d1aee063dec at https://mate-desktop.github.io/mate-panel/

**Comment by yetist** [comment]
Clang Analyzer results of 4a3b79d04ce89a6b5ff88ed8e31c36ed280f2dd7 at https://mate-desktop.github.io/mate-panel/

**Comment by sc0w** [comment]
@yetist  the web https://mate-desktop.github.io/mate-panel/ doesn't work here (404 error)

**Comment by yetist** [comment]
@raveit65  Can you reset  github pages to use `gh-pages` branch?

**Comment by raveit65** [comment]
Done, and page is there.
@sc0w

**Comment by lukefromdc** [comment]
Just beginning to go over that report. Some of the dead assignments appear to be nothing more than initializing variables. The security issues (two of them) are string handling issues. There are some invalid casts regarding structures, several garbage values used, and two null pointer dereference issues. What I do NOT see here (or maybe its here but I don't know enough to recognize it) is that nasty memory leak with applets being resized that nobody has been able to find, the one that has caused trouble for some Fedora users if the tray is built in-process or seconds are showing on a (in process?) clock.

**Comment by sc0w** [comment]
I see WIP in the title, so, I suppose the PR isn't ready for the author

**Comment by yetist** [comment]
[Notification]: Clang Analyzer results of 1461e905341dc976774dc3d784af6dadd6aa1b61 at https://mate-desktop.github.io/mate-panel/

**Comment by yetist** [comment]
[Notification]: Clang Analyzer results of 12f18a189d5b1e68d4887e869c56797f62792379 at https://mate-desktop.github.io/mate-panel/

**Comment by yetist** [comment]
[Notification]: Clang Analyzer results of a691ee73344aedfa8a9690c8a381ea8ceb9c1d46 at https://mate-desktop.github.io/mate-panel/

**Comment by yetist** [comment]
Now it's ready.

**Comment by sc0w** [comment]
how many reports will be displayed in the web?

**Comment by yetist** [comment]
Default is the last 10 results.

**Comment by sc0w** [comment]
I think it is good idea to keep always the report of git master there, and it can be compared with report of PRs (but this can be done in other PR).

Another question, I don't like the notifications, it will be spam in all the PRs in all new commits, @mate-desktop/core-team do you like the auto-notifications ?

**Comment by raveit65** [comment]
Which notification?

**Comment by sc0w** [comment]
@raveit65  you can see in previous comments here, it was automatically, for example:

> [Notification]: Clang Analyzer results of a691ee7 at https://mate-desktop.github.io/mate-panel/

**Comment by lukefromdc** [comment]
Would those be fixed threads that can be muted in terms of email and notifications?

**Comment by yetist** [comment]
Now that we can use https://mate-panel.mate-desktop.dev/ to see the clang analyzer results, it feels good.

**Comment by sc0w** [comment]
It seems now https://mate-desktop.github.io/mate-panel redirects to https://mate-panel.mate-desktop.dev and the server doesn't work

**Comment by yetist** [comment]
@sc0w 

Now it works, you can try it again.
BTW, caja and marco subdomains all works, they are https://caja.mate-desktop.dev and https://marco.mate-desktop.dev

**Comment by yetist** [comment]
Now use status notification like this:

image

**Comment by yetist** [comment]
Rebase on master branch, and switch to use build scripts on master branch.

**Comment by raveit65** [comment]
Let the beast run.

**Pull request merged**
