### PR TITLE
Gtk3: Support icon-padding and icon-size for NotificationArea applet

### PR DESCRIPTION
**Pull request by dnk**
Merge gnome-panel changes
Fix for https://github.com/mate-desktop/mate-panel/issues/189

Known issues: na-tray lost real transparency with gtk3

### CODE REVIEW

**Comment by flexiondotorg** [comment]
@stefano-k Please review this for inclusion in MATE 1.10

**Comment by NiceandGently** [comment]
@dnk 
> Known issues: na-tray lost real transparency with gtk3

Is this before or after your PR?

**Comment by monsta** [comment]
This is big change anyway, let's leave this for 1.11 development phase.

**Comment by infirit** [comment]
>Known issues: na-tray lost real transparency with gtk3

Transparency was ok for me when I tested this week.

It works fine in both Gtk versions so could be merged IMO..

**Comment by infirit** [comment]
Merged

**Comment by NiceandGently** [comment]
see https://github.com/mate-desktop/mate-panel/issues/336

**Pull request closed without merging**
