### PR TITLE
Clock applet help: To Adjust the System Date or Time

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by rbuj** [comment]
@lukefromdc 
"then the mate-polkit dialog prompts for the administration password."

AUTHENTICATION AGENTS section:
https://www.freedesktop.org/software/polkit/docs/latest/polkit.8.html

**Comment by lukefromdc** [comment]
The actual line is 

 <para>Press the <guibutton>Set System Time</guibutton> button, then the <guilabel>Authenticate</guilabel> dialog is shown asking for authentication. Enter the <literal>root</literal> password and press the <guibutton>Authenticate</guibutton> button.

and on my system the resulting output is

Press the Set System Time button, then the Authenticate dialog is shown asking for authentication. Enter the root password and press the Authenticate button.

**Comment by rbuj** [comment]
Proposal code (escaped string):
&lt;para&gt;Press the &lt;guibutton&gt;Set System Time&lt;/guibutton&gt; button, then the &lt;guilabel&gt;mate-polkit&lt;/guilabel&gt; dialog prompts for the administration password.
&lt;/para&gt;

Proposal result:
Press the Set System Time button, then the mate-polkit dialog prompts for the administration password.

**Comment by lukefromdc** [comment]
I just tested that and it works. Might be better to use 

            <para>Press the <guibutton>Set System Time</guibutton> button, then the <guilabel>mate-polkit</guilabel> dialog prompts for the administration password. Enter the administration password and press the Authenticate button
            </para>

About to test

**Comment by lukefromdc** [comment]
Last proposed option I just posted works fine in a local test. Did not merge and then add a final commit for this because I can't get distcheck to work (even with today's master) and this may affect translations.

**Pull request merged**
