### PR TITLE
Spelling: apps, … spaced comma

### PR DESCRIPTION
**Pull request by comradekingu**

### CODE REVIEW

**Comment by raveit65** [comment]
For me `applications` is the correct pronunciation.
... mate-panel isn't a smart-phone application ;-)

**Comment by comradekingu** [comment]
@raveit65 Habitual edit. I still stick to "Programs", to fully avoid the connotation to what are essentially widgets.

**Comment by comradekingu** [comment]
@raveit65 Doing "apps" only adds a level of inconsistency over saving space. "Applications" is used throughout, with "Programs" as the runner up.

**Comment by raveit65** [comment]
merged https://github.com/mate-desktop/mate-panel/commit/a63f21ae4e7f268fc7c9714829f4a83e1a76a93b
Thanks

**Pull request closed without merging**
