### PR TITLE
Na-tray deprecations

### PR DESCRIPTION
**Pull request by raveit65**
Please test.

### CODE REVIEW

**Comment by raveit65** [comment]
@lukefromdc 
Oh. i tested only with composite enable. Can you test only `na-tray: avoid deprecated g_type_class_add_private commit please?

**Comment by raveit65** [comment]
Confirmed, `na-tray: avoid deprecated gdk_display_supports_composite` was the culprit.
I dropped this commit from PR. Should be work now.
Thanks and please test again.

**Comment by raveit65** [comment]
Culprit commit was already reverted by Albert.
https://gitlab.gnome.org/GNOME/gnome-panel/commit/e73b4a9cbb88d5fb6797efc409c494e0f53ac179

**Comment by muktupavels** [comment]
That is what you get when blindly replacing deprecated functions without checking what they do...

https://gitlab.gnome.org/GNOME/gtk/blob/gtk-3-24/gdk/gdkdisplay.c#L1885
https://gitlab.gnome.org/GNOME/gtk/blob/gtk-3-24/gdk/x11/gdkdisplay-x11.c#L2631

https://gitlab.gnome.org/GNOME/gtk/blob/gtk-3-24/gdk/gdkscreen.c#L1001
https://gitlab.gnome.org/GNOME/gtk/blob/gtk-3-24/gdk/x11/gdkscreen-x11.c#L361

https://gitlab.gnome.org/GNOME/gtk/blob/gtk-3-24/gdk/gdkwindow.c#L7400
https://gitlab.gnome.org/GNOME/gtk/blob/gtk-3-24/gdk/x11/gdkwindow-x11.c#L5486

Apparently at that time I did not look at gtk code.

**Comment by raveit65** [comment]
@muktupavels 
So this commit is broken too?
`na-tray: avoid deprecated g_type_class_add_private`
Or about what are you talking?

**Comment by raveit65** [comment]
@mate-desktop/core-team 
Calling again the team for a review after 8 days.
***The more you review other PRs from team as faster your PRs will be reviewed.***

**Comment by lukefromdc** [comment]
Should I go ahead and merge this?

**Comment by raveit65** [comment]
Thanks for the reviews.
@mate-desktop/core-team 
To all others , don't expect that i will spend my spare time for your reviews in future.

**Pull request merged**
