### PR TITLE
Enable Travis CI support

### PR DESCRIPTION
**Pull request by yetist**
It's ready to go.

### CODE REVIEW

**Comment by raveit65** [comment]
Ok, runs fine with latest changes from https://github.com/mate-desktop/mate-dev-scripts/pull/10
But why does distcheck not run here?
https://travis-ci.org/mate-desktop/mate-panel/jobs/488999917

**Comment by yetist** [comment]
run with `make distcheck >/dev/null`, start at line 4232, and return 0 at 4266 line.

**Comment by raveit65** [comment]
That means it was running but it isn't printed?

**Comment by yetist** [comment]
`make distcheck` only failed on debian system and succeeded on other distro.
logs on debian: 
https://travis-ci.org/mate-desktop/mate-panel/jobs/488999916

**Comment by raveit65** [comment]
Ok, than the `return 0` means it was running successful.
I missed the full output. But OK.

**Pull request merged**
