### PR TITLE
Add panel-ditem-editor-dialog.ui

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Review by lukefromdc — COMMENTED** [review]
We have a problem here: the edit dialog for panel launchers comes up in a CSD window instead of a normal server-side decorated window with this

**Comment by rbuj** [comment]
@lukefromdc It's because of overriding the constructed method in class_init. It should be fixed now.

**Review by lukefromdc — APPROVED** [review]
This now works as expected, the panel editor dialog comes up in a normal server-side decorated window same as in master, the interface looks the same as in master,  and changes to a launcher are applied as expected

**Comment by raveit65** [comment]
@rbuj 
There are new build warnings.
https://travis-ci.org/github/mate-desktop/mate-panel/jobs/764207037#L4125
```
panel-ditem-editor.c:522:1: warning: unused function 'grid_attach_label' [-Wunused-function]

grid_attach_label (GtkGrid *grid, GtkWidget *label, int left, int top, int width, int height)

^

panel-ditem-editor.c:528:1: warning: unused function 'grid_attach_entry' [-Wunused-function]

grid_attach_entry (GtkGrid *grid, GtkWidget *entry, int left, int top, int width, int height)
```
I don't see them in latest build of master.
https://travis-ci.org/github/mate-desktop/mate-panel/jobs/762014264

**Comment by rbuj** [comment]
@raveit65 done

**Comment by lukefromdc** [comment]
Just tested again, launcher editing dialog behavior seems to be same as in master as expected

**Review by raveit65 — APPROVED** [review]
LGTM,
dialog comes up fine, deprecation is fixed, and no new warnings are generated.
Looks good to go.

**Pull request merged**
