### PR TITLE
support desktop actions

### PR DESCRIPTION
**Pull request by dnk**

### CODE REVIEW

**Comment by lukefromdc** [comment]
I'm not sure what "desktop actions" are in this context but a build of this branch worked fine. Looking over the code I do see some general updating as well. The changes will need to be rebased, as your branch has diverged over time and gives a messy commit history and changelog in a test merge in a dummy repo.

**Comment by dnk** [comment]
evolution's desktop actions
image
described at https://github.com/GNOME/evolution/blob/master/data/evolution.desktop.in.in

**Comment by raveit65** [comment]
I saw those actions in gnome-terminal desktop file a while ago, now i know for what is good for.

**Comment by raveit65** [comment]
It works fine with gedit as panel launcher.
And deprecated GtkStock is replaced with GIcon w/o removing icons from menus.
So it looks OK with a quick run test of the panel.
I tested this with a build from git master.

**Comment by raveit65** [comment]
Btw. looks like that firefox desktop file use desktop actions too.

**Comment by lukefromdc** [comment]
Merged with https://github.com/mate-desktop/mate-panel/commit/7ee450758e4f2bee13aa8ff967a5795a6dcdc91f

**Pull request closed without merging**
