### PR TITLE
Memory leak fixes

### LINKED ISSUE #1085: high memory usage - mate-panel
#### Expected behaviour
mate-panel does not consume 13G of memory

#### Actual behaviour
mate-panel consumes 13G memory over two to three days of uptime

#### Steps to reproduce the behaviour
Nothing specific. The system runs on mate-desktop-environment and used for day-to-day activities like browsing, chat.

#### MATE general version
MATE Desktop Environment - 1.24.0

#### Package version
mate-panel-1.24.0-4.fc32.x86_64

#### Linux Distribution
Fedora release 32 (Thirty Two)
5.6.13-300.fc32.x86_64

#### Additional information about memory usage
free -h
              total        used        free      shared  buff/cache   available
Mem:           30Gi        27Gi       1.5Gi       319Mi       1.3Gi       2.1Gi
Swap:         4.4Gi        44Mi       4.3Gi

image

### PR DESCRIPTION
**Pull request by tbzatek**
A bunch of tiny fixes found by valgrind.

Please test if this fixes #1085

### CODE REVIEW

**Comment by lukefromdc** [comment]
Note that memory use still rises with time of use, though as I said there are a LOT of other memory leaks in the panel. Still, this is a start

**Comment by lukefromdc** [comment]
Called core team for another review if anyone gets the time. Should I merge this if nobody does?

**Comment by tbzatek** [comment]
Thanks for testing, this is impressive. I'll keep opening separate pull requests for future fixes (if any).

After nearly 24h idle I don't see any memory consumption increase, `mate-panel` stays at 40MB RSS with out-of-process applets sitting around 35 MB each. `wnck`, `netspeed`, `notification-area` and `clock` applets as processes. Previously at this setup I got several GB resident memory size after couple of days of regular use.

That said there might be other leaks in features I don't regularly use, let's see if I can reproduce some more.

Also many of the _indirect_ leaks are singletons sitting there for the rest of the application lifecycle, such as the font or icon cache, theming, etc.

**Comment by raveit65** [comment]
The leaks are dramatic when compile in-process, see bug report.

**Comment by lukefromdc** [comment]
Is this ready to merge or is this expected to be part of another PR later?

**Comment by tbzatek** [comment]
> Is this ready to merge or is this expected to be part of another PR later?

You can merge this one. I tend to open separate pull requests for easier reviewing and to get fixes in in batches. If a single big pull request works for you better, I can rebase #1113 for example.

**Comment by raveit65** [comment]
And cherry-picked to stable 1.24 branch.
Thanks for this support by you and RedHat :)

**Comment by raveit65** [comment]
By the way,
greatest memory consumption was reported here https://bugzilla.redhat.com/show_bug.cgi?id=1830885
Build-in-process and reporter use wine and amule notification-area applet and did run his box several days.
This is something which i can't /don't want to test.
I switched back to build applets out-of-process to close this rhbz report.
But this blocks wayland support.

**Comment by tbzatek** [comment]
> And cherry-picked to stable 1.24 branch.
> Thanks for this support by you and RedHat :)

Thanks! For the record, this is my private initiative and I can't afford investing much time in this, just using my single (company) GitHub account and debugging on-the-go while doing my day job (spoiler: https://github.com/storaged-project/udisks/).

**Pull request merged**
