### PR TITLE
wncklet: center preview windows

### LINKED ISSUE #1315: Improve Windows List Thumbnail Positioning
#### Expected behaviour
Position the window thumbnails horizontally near the center or exactly the center of each window items, similar to how the text tooltips adjust their position so that they won't feel sitting right between 2 window list items.

#### Actual behaviour
Current window thumbnails, if enabled, put its horizontal position exactly the center of where the mouse cursor first touch the window list item unless the thumbnail would have overflown outside display surface. It is confusing as which window list item an thumbnail belongs may be visually unclear. The inconsistent positioning that cares too much where my mouse begins the hovering is frustrating. I end up disabling this feature after experimenting it a few while in Linux Mint, whereas I feel no problem keeping it on in Windows 10.

#### Steps to reproduce the behaviour
Enable Window Thumbnails in Window List Preferences

#### MATE general version
1.26

#### Package version
mate-panel
1.26.1.1mint1+una

#### Linux Distribution
Linux Mint 20.3 Una 64-bit

#### Link to bugreport of your Distribution (requirement)
https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/where.html#mate-bugs-github-mate-desktop said I should report it right here unless it "relates to mintmenu, mintdesktop or a mint theme in MATE", so... I hope I am law-abiding here.

### PR DESCRIPTION
**Pull request by balazs-endresz**
Fixes #1315 

Instead of randomly positioning the preview windows over the window list applet this centers them properly.

I've tested it on Ubuntu 22.04, with all orientations, 2x scaling, many windows opened (so that previews are not cut off at the edges), and at least plugging in a secondary monitor didn't cause any issues either.

One thing that might be worth pointing out is `gtk_window_set_position + GTK_WIN_POS_MOUSE` followed by `gtk_window_get_position` returned incorrect coordinates: e.g. it was zero for the first about 40 pixels. So this gets the mouse position differently. This newer method is actually also used in `panel_toplevel_contains_pointer`.

The tooltips are still not aligned properly but I think that could be done in a follow up. Maybe even in `libwnck` instead. I might give that a try at some point.

### CODE REVIEW

**Review by lukefromdc — COMMENTED** [review]
We get two new build warnings about incompatable pointers with this, despite the build warnings this the window list and previews still work, and this does center the preview windows.

Unknown if the compiler is working around this or not, but with these warnings I would not expect this code to work with all compilers and all systems:

```
window-list.c: In function 'preview_window_reposition':
window-list.c:336:78: warning: passing argument 1 of 'gtk_widget_get_parent' from incompatible pointer type [-Wincompatible-pointer-types]
  336 |         gdk_window_get_origin (gtk_widget_get_window (gtk_widget_get_parent (tl)), &x_offset, &y_offset);
      |                                                                              ^~
      |                                                                              |
      |                                                                              WnckTasklist * {aka struct _WnckTasklist *}
In file included from /usr/include/gtk-3.0/gtk/gtkapplication.h:27,
                 from /usr/include/gtk-3.0/gtk/gtkwindow.h:33,
                 from /usr/include/gtk-3.0/gtk/gtkdialog.h:32,
                 from /usr/include/gtk-3.0/gtk/gtkaboutdialog.h:30,
                 from /usr/include/gtk-3.0/gtk/gtk.h:31,
                 from ../../libmate-panel-applet/mate-panel-applet.h:30,
                 from window-list.c:15:
/usr/include/gtk-3.0/gtk/gtkwidget.h:896:72: note: expected 'GtkWidget *' {aka 'struct _GtkWidget *'} but argument is of type 'WnckTasklist *' {aka 'struct _WnckTasklist *'}
  896 | GtkWidget           * gtk_widget_get_parent             (GtkWidget    *widget);
      |                                                          ~~~~~~~~~~~~~~^~~~~~
window-list.c:360:55: warning: passing argument 1 of 'gtk_container_get_children' from incompatible pointer type [-Wincompatible-pointer-types]
  360 |         GList* children = gtk_container_get_children (tl);
      |                                                       ^~
      |                                                       |
      |                                                       WnckTasklist * {aka struct _WnckTasklist *}
In file included from /usr/include/gtk-3.0/gtk/gtkbin.h:33,
                 from /usr/include/gtk-3.0/gtk/gtkwindow.h:35:
/usr/include/gtk-3.0/gtk/gtkcontainer.h:169:62: note: expected 'GtkContainer *' {aka 'struct _GtkContainer *'} but argument is of type 'WnckTasklist *' {aka 'struct _WnckTasklist *'}
  169 | GList*   gtk_container_get_children     (GtkContainer       *container);
      |                                          ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
```

**Comment by balazs-endresz** [comment]
Thanks, I've just added those in.

**Review by lukefromdc — APPROVED** [review]
Approving as this now builds with only deprecation warnings and no new ones, and works fine. Thanks!

**Comment by balazs-endresz** [comment]
And I forgot to test this with grouping enabled. I'll add another PR soon, that shouldn't be too difficult to fix now.

**Pull request merged**
