### PR TITLE
Down-scale out-of-process applets on HiDPI displays

### PR DESCRIPTION
**Pull request by vkareh**
Out-of-process applets end up scaled up doubly. This divides the preferred width/height by the scale factor to ensure they are back at the correct preferred size.

For this change I had to move the GTK_VERSION guards on the `get_preferred_width/height` methods. The methods are now exposed, but the focus style class padding is still guarded.

### CODE REVIEW

**Comment by lukefromdc** [comment]
Others on the team should have a look at this too, of course

**Comment by lukefromdc** [comment]
The GTK version guards will soon become unnecessary, as MATE 1.20 is going to be GTK3.22-only. We will be able to drop all the old code blocks at that point, so no need to test with anything but GTK 3.22

**Comment by flexiondotorg** [comment]
Tested on my XPS 15 and this resolves the issue with out-process applet allocation too much space on the panel. I see no regressions when using a LoDPI display.

**Comment by monsta** [comment]
@vkareh: I hope the code is still correct after https://github.com/mate-desktop/mate-panel/pull/723 (where all `GTK_CHECK_VERSION` blocks are removed).

**Pull request merged**
