### PR TITLE
desktop actions support

### PR DESCRIPTION
**Pull request by dnk**
required glib>=2.38
append desktop actions to launcher's menu
launch desktop actions

### CODE REVIEW

**Comment by flexiondotorg** [comment]
@stefano-k Please review this for inclusion in MATE 1.10

**Comment by NiceandGently** [comment]
@dnk 
I tested it with 1.8.x (>glib2-38) in fedora 20/21, in result desktop launcher stop working.
This happends if i try to start a launcher
```
[rave@fedora-21 Schreibtisch]$ mate-panel --replace

(mate-panel:1698): GLib-GIO-CRITICAL **: g_desktop_app_info_launch_action: assertion 'app_info_has_action (info, action_name)' failed

(mate-panel:1698): GLib-GIO-CRITICAL **: g_desktop_app_info_launch_action: assertion 'app_info_has_action (info, action_name)' failed

(mate-panel:1698): GLib-GIO-CRITICAL **: g_desktop_app_info_launch_action: assertion 'app_info_has_action (info, action_name)' failed
``` 
Is this commit for 1.10 only?

**Comment by monsta** [comment]
Which "actions" are meant here?

**Comment by dnk** [comment]
spec http://standards.freedesktop.org/desktop-entry-spec/latest/ar01s10.html
unity implementation https://help.ubuntu.com/community/UnityLaunchersAndDesktopFiles

**Comment by monsta** [comment]
Ok good, but since it's a new feature and quite a big commit, I think we better leave that open until the development of 1.11 starts.

**Comment by monsta** [comment]
Whoops, merge conflict

**Comment by raveit65** [comment]
@dnk is there any chance to get this working with current master?

**Pull request closed without merging**
