### PR TITLE
Use dashes instead of underscores in signal names

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Review by lukefromdc — APPROVED** [review]
This builds and runs fine, note that when changing time zones to test signals the time itself has to update in order for the change to be reflected in the clock applet, same as with master

**Comment by raveit65** [comment]
Hmm, i guess this is needed because of glade changes in UI files?

**Comment by rbuj** [comment]
Both cases are recognized by g_signal. The underscores are also valid, but they are no longer used in new code, as well as you said, glade uses dashes.

**Review by raveit65 — APPROVED** [review]
LGTM

**Pull request merged**
