### PR TITLE
update to use the latest submodule code

### LINKED ISSUE #1091: Panel fails to register with session manager (blocking caja etc), times out at startup since git submodule commit
#### Expected behaviour
mate-panel starts normally, the applets start normally, and the session finishes starting

#### Actual behaviour
Panel starts with session but not all applets show-and caja does NOT start for a while nor does anything after it. Eventually panel registration with mate-session-manager times out and other applications start. This warning appears in .xsession-errors:
`
mate-session[4918]: WARNING: Application 'mate-panel.desktop' failed to register before timeout`
reverting https://github.com/mate-desktop/mate-panel/commit/1cfcb58dd5bc3e6effac1d2cdbc482dce930dd9b restores normal session startup behavior

#### Steps to reproduce the behaviour
Install mate-panel built from git master after https://github.com/mate-desktop/mate-panel/commit/1cfcb58dd5bc3e6effac1d2cdbc482dce930dd9b and start a new session

#### MATE general version
1.24 from git master

#### Package version
local builds current as of 6-12-2020 and a second build on 6-14-2020(same code new pull)

#### Linux Distribution
Debian Unstable

#### Link to downstream report of your Distribution
None as this is a local build

### PR DESCRIPTION
**Pull request by yetist**
The latest code of mate-modules can fix #1091

### CODE REVIEW

**Comment by raveit65** [comment]
With master:
```
Submodule 'mate-panel/mate-submodules' (https://github.com/mate-desktop/mate-submodules.git) registered for path 'mate-panel/mate-submodules'
Cloning into '/media/Data/Programme/Linux/Mate-Desktop/git-version/github-matedesktop/mate-panel-dist/mate-panel/mate-submodules'...
Submodule path 'mate-panel/mate-submodules': checked out '2a986e57505e92f606f57fcec4b28e171f89a005'
```
With this branch:
```
[rave@mother mate-panel-dist]$ git submodule init && git submodule update
Submodule 'mate-panel/mate-submodules' (https://github.com/mate-desktop/mate-submodules.git) registered for path 'mate-panel/mate-submodules'
Cloning into '/media/Data/Programme/Linux/Mate-Desktop/git-version/github-matedesktop/mate-panel-dist/mate-panel/mate-submodules'...
Submodule path 'mate-panel/mate-submodules': checked out '799639b54e6e5c2b04a3cd13610ebe54d21b71af'
```
@yetist
LGTM, but can you please explain what you did?
So that we can do the same if necessary.

And don't we need `#ifdef HAVE_X11 || GDK_WINDOWING_X11` for mate-panel?

**Comment by yetist** [comment]
> LGTM, but can you please explain what you did?
> So that we can do the same if necessary.

I use the following ways to make changes:
```
cd mate-panel/mate-submodules/
git fetch/checkout/log ...       # you can run git commands here.
cd ../..
git status
git commit
```
 
> And don't we need `#ifdef HAVE_X11 || GDK_WINDOWING_X11` for mate-panel?

I'm not sure, but I think other repos that use mate-submodules may not define the HAVE_X11 macro.

**Comment by raveit65** [comment]
> I'm not sure, but I think other repos that use mate-submodules may not define the HAVE_X11 macro.

I mean an `or` condition.
`HAVE_X11` for mate-panel and `GDK_WINDOWING_X11` for the other repos.
Mate-panel needs definitely `HAVE_X11`, see https://github.com/mate-desktop/mate-panel/blob/master/configure.ac#L215

**Comment by raveit65** [comment]
> > LGTM, but can you please explain what you did?
> > So that we can do the same if necessary.
> 
> I use the following ways to make changes:
> 
> ```
> cd mate-panel/mate-submodules/
> git fetch/checkout/log ...       # you can run git commands here.
> cd ../..
> git status
> git commit
> ```

This doesn't work here to update mate-submodul to latest commit.
I am on 
```
mate-submodules'...
Submodule path 'mate-panel/mate-submodules': checked out '2a986e57505e92f606f57fcec4b28e171f89a005'
```
after your commands.
In other words, what did you do to create changes for this PR?

**Comment by yetist** [comment]
Please try  to do it like this:
```bash
$ git status
On branch master
nothing to commit, working tree clean
$ git submodule status
 2a986e57505e92f606f57fcec4b28e171f89a005 mate-panel/mate-submodules (2a986e5)
$ cd mate-panel/mate-submodules/
$ git fetch origin
$ git checkout master
Previous HEAD position was 2a986e5 use subdir libegg
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
$ git log -n 1
commit 799639b54e6e5c2b04a3cd13610ebe54d21b71af (HEAD -> master, origin/master, origin/HEAD)
Author: rbuj <robert.buj@gmail.com>
Date:   Tue Jun 16 14:44:16 2020 +0200

    Remove GDK_WINDOWING_QUARTZ & GDK_WINDOWING_WIN32 support
$ cd ../..
$ git status
On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   mate-panel/mate-submodules (new commits)

no changes added to commit (use "git add" and/or "git commit -a")
$ git submodule status
+799639b54e6e5c2b04a3cd13610ebe54d21b71af mate-panel/mate-submodules (heads/master)
```

**Comment by raveit65** [comment]
Weird, something is missing here:
```
[rave@mother mate-panel-dist]$ LANG=C
[rave@mother mate-panel-dist]$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
[rave@mother mate-panel-dist]$ git submodule status
-2a986e57505e92f606f57fcec4b28e171f89a005 mate-panel/mate-submodules
[rave@mother mate-panel-dist]$ cd mate-panel/mate-submodules/
[rave@mother mate-submodules]$ git fetch origin
[rave@mother mate-submodules]$ git checkout master
Already on 'master'
Your branch is up to date with 'origin/master'.
[rave@mother mate-submodules]$ git log -n 1
commit b208cfea6a66f7427be320469040d6927e42ff1b (HEAD -> master, origin/master, origin/HEAD)
Author: raveit65 <mate@raveit.de>
Date:   Mon Jun 15 11:30:23 2020 +0200

    pre-bump version
[rave@mother mate-submodules]$ cd ../..
[rave@mother mate-panel-dist]$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
[rave@mother mate-panel-dist]$ git submodule status
-2a986e57505e92f606f57fcec4b28e171f89a005 mate-panel/mate-submodules
```

**Comment by raveit65** [comment]
With `git submodule init && git submodule update --recursive --remote` i can pull latest changes + files.
But only updating to latest commit without pulling in the files doesn't work for me :/
....given up....

**Comment by yetist** [comment]
@raveit65 

Please read this document: https://git-scm.com/book/en/v2/Git-Tools-Submodules

**Pulling in Upstream Changes from the Submodule Remote**

If you want to check for new work in a submodule, you can go into the directory and run `git fetch` and `git merge` the upstream branch to update the local code.

There is an easier way to do this as well, if you prefer to not manually fetch and merge in the subdirectory. If you run `git submodule update --remote`, Git will go into your submodules and fetch and update for you.

**Comment by raveit65** [comment]
@yetist 
Thanks, but you didn't understand my question or problem.
The problem was to avoid pulling files from submodule repo, like you did for this PR
I only wanted to update the commit hash of submodule repo inside a host repo.
Well, i can delete all files by hand before commiting an update.
```
[rave@mother mate-panel-dist]$ LANG=C
[rave@mother mate-panel-dist]$ git submodule init && git submodule update --remote
Submodule 'mate-panel/mate-submodules' (https://github.com/mate-desktop/mate-submodules.git) registered for path 'mate-panel/mate-submodules'
Cloning into '/media/Data/Programme/Linux/Mate-Desktop/git-version/github-matedesktop/mate-panel-dist/mate-panel/mate-submodules'...
Submodule path 'mate-panel/mate-submodules': checked out 'cb356c84294989cf114bc047c831e27d7ce98b94'
[rave@mother mate-panel-dist]$ ls -l mate-panel/mate-submodules/
total 12
-rw-rw-r-- 1 rave rave   17 Jun 18 17:33 Makefile.am
-rw-rw-r-- 1 rave rave 1918 Jun 18 17:33 configure.ac
drwxrwxr-x 2 rave rave 4096 Jun 18 17:33 libegg
[rave@mother mate-panel-dist]$ rm -rf mate-panel/mate-submodules/*
[rave@mother mate-panel-dist]$ ls -l mate-panel/mate-submodules/
total 0
rave@mother mate-panel-dist]$ git submodule status 
+cb356c84294989cf114bc047c831e27d7ce98b94 mate-panel/mate-submodules (heads/master)
```

**Comment by yetist** [comment]
@raveit65 

You need this?

```bash
$ git status
On branch mytest
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	modified:   mate-panel/mate-submodules

$ git diff
diff --git a/mate-panel/mate-submodules b/mate-panel/mate-submodules
index 799639b5..cb356c84 160000
--- a/mate-panel/mate-submodules
+++ b/mate-panel/mate-submodules
@@ -1 +1 @@
-Subproject commit 799639b54e6e5c2b04a3cd13610ebe54d21b71af
+Subproject commit cb356c84294989cf114bc047c831e27d7ce98b94
$ git submodule status
+cb356c84294989cf114bc047c831e27d7ce98b94 mate-panel/mate-submodules (heads/master)
$ git add mate-panel/mate-submodules/
$ git commit -m 'update submodule'
[mytest 7cd473ab] update submodule
 1 file changed, 1 insertion(+), 1 deletion(-)
```

**Comment by raveit65** [comment]
No, since several years i know to commit with git :)

**Comment by raveit65** [comment]
Ok , got it, thanks

**Comment by tamplan** [comment]
Not sure and sorry to mention this here but perhaps the "po/POTFILES.skip" should be updated to include:
`mate-panel/mate-submodules/libegg/eggdesktopfile.c`

The po files generated mention this line for me by error.

Regards

**Comment by raveit65** [comment]
@tamplan 
did you pulled in libegg files with `git submodule init && git submodule update --remote`, before building?

**Comment by tamplan** [comment]
Yes, i do.

**Comment by raveit65** [comment]
Build log with error?

**Comment by tamplan** [comment]
No error, the project is correctly build. I was translating fr.po with Geany to harmonize translations between others projects and see the line i mention.

**Comment by raveit65** [comment]
I don't understand your intention to edit *.po files
We use transifex server for our translations.
And eggdesktopfile.c has translations, so POTFILES.in is the right place.
Without seeing your error i don't understand what you mean.

**Comment by tamplan** [comment]
i use transifex cli client to translate more easly and quickly and use a text editor to copy/paste same strings between the Mate reposiroty.
In French, we must use special characters like « or » and NBSP before : , more doable with gtranslator (NBSP is correctly shown for example).

**Comment by tamplan** [comment]
I have these lines in "fr.po" of mate-panel:
`#: mate-panel/mate-submodules/libegg/eggdesktopfile.c:1185
#, c-format
msgid "Unrecognized launch option: %d"
msgstr "Option de lancement non reconnue : %d"

#: mate-panel/mate-submodules/libegg/eggdesktopfile.c:1401
msgid "Can't pass document URIs to a 'Type=Link' desktop entry"
msgstr ""
"Impossible de passer les URI de documents vers une entrée .desktop de type "
"« Type=Link »"`

I not understand why there are here and in "fr.po" of libegg, perhaps it's not a problem like i said before.

**Comment by raveit65** [comment]
No idea, in de.po it looks like this....
```
#: mate-panel/mate-submodules/libegg/eggdesktopfile.c:1185
#, c-format
msgid "Unrecognized launch option: %d"
msgstr "Nicht erkannte Startoption: »%d«"

#: mate-panel/mate-submodules/libegg/eggdesktopfile.c:1401
msgid "Can't pass document URIs to a 'Type=Link' desktop entry"
msgstr ""
"Dokumentadressen können nicht auf einen Schreibtischeintrag des Typs »Link« "
"angewendet werden"
```

PS: i quoted you posting for you......this is better to avoid linking reports with numbers in your post.

**Comment by tamplan** [comment]
Yes thanks for quoting.

**Pull request merged**
