### PR TITLE
fix panel reset problems

### PR DESCRIPTION
**Pull request by monsta**
Fixes https://github.com/mate-desktop/mate-panel/issues/436

How to test:

1. Resetting the panel layout

- use `mate-panel --reset` to reset the panel(s) to the current default layout
- use `mate-panel --reset --layout=<layout_name>` to set the new default layout and reset the panel(s) to it
- the panel should not crash
- the panel should reappear with the default layout

2. Deleting one panel in a multi-panel layout

- use "Delete this panel" menu item from the right-click menu to delete that panel
- the panel should not crash (https://github.com/mate-desktop/mate-panel/issues/65 should not happen again)

Both problems I've described in https://github.com/mate-desktop/mate-panel/issues/436#issuecomment-491845638 can be more often reproduced in Ubuntu than in Debian Testing, for example. That's the problem of race condition issues...

### CODE REVIEW

**Comment by lukefromdc** [comment]
This is something I cannot test except when I am doing nothing else due to my bare-metal only setup and heavily customized panel layout that can take 1/2 hour to redo

**Comment by flexiondotorg** [comment]
@lukefromdc You can save/restore your panel layouts using MATE Tweak, it's in the Debian archive as `mate-tweak` or available here https://github.com/ubuntu-mate/mate-tweak

@monsta I'm testing this and will report back later.

**Comment by lukefromdc** [comment]
Mate-tweak mostly works, but I got a ton of python errors, lost all custom launchers except GIMP, and the configuration of both the clock and system monitor applets. Will test this now before restoring

**Comment by lukefromdc** [comment]
Just duplicated the crash so I have a baseline

**Comment by lukefromdc** [comment]
The mate-tweak stuff has one benefit despite having to rebuild my launcher layout:greaty cleaned up my dconf database for mate-panel. This came from the same issue that trashed my launchers: not saving numbered objects that lack a unique name (launchers do have names but the panel does not use them it seems)..

**Comment by monsta** [comment]
The test for deleting the panel is just to make sure there's no regression, and #65 won't appear again. That's because I've removed the code that fixed #65 and replaced it with similar code in toplevel's dispose function.

**Comment by lukefromdc** [comment]
I can't reproduce a crash on panel removal now with or without this applied, so good on this end

**Comment by lukefromdc** [comment]
Is this ready to go or are we still waiting on @vkareh ?

**Comment by monsta** [comment]
Thanks, merged. Will pick this to 1.22 and 1.20 too.

**Pull request merged**
