### PR TITLE
travis: use f28 with old libmatemenu

### PR DESCRIPTION
**Pull request by raveit65**
with a docker-image with MATE 1.20

### CODE REVIEW

**Comment by raveit65** [comment]
@yetist 
Any idea what we should do with build for archlinux after arch use 1.22 docker-image?
Or should we simply set building disable for 1.20 branch?
I mean archlinux don't need any 1.20 package any more as rolling release, or not?

**Comment by yetist** [comment]
> I mean archlinux don't need any 1.20 package any more as rolling release, or not?

Yes, archlinux don't need any 1.20 package any more, now is 1.22.

**Comment by yetist** [comment]
There is a way to use archlinux on travis: in the `before_scripts` of archlinux, download the mate-menus-1.20 tarball and install it, But this is not worth it, archlinux does not need 1.20.

A similar abi change problem, there will be a better solution after moving to meson in the future, meson supports subproject, as used here: https://gitlab.gnome.org/GNOME/gtk/tree/master/subprojects

**Comment by raveit65** [comment]
So, do you agree with disable archlinux for 1.20 branches with ABI changes?

**Comment by yetist** [comment]
Yes, I agree.

**Comment by monsta** [comment]
We can also switch Debian from Sid to Buster for 1.20. Debian Sid (and Testing) will get 1.22 once Buster is released as the next Debian Stable this year. This might happen even this summer, given that Buster is in freeze for almost a half of year already, and Debian releases usually happen mid-year.

**Comment by raveit65** [comment]
Feel free to test and commit this.

**Comment by monsta** [comment]
Created https://github.com/mate-desktop/mate-panel/pull/975 for that, let's see how it builds.

**Pull request merged**
