### PR TITLE
menu: fix crash when some .desktop file has empty Icon field

### PR DESCRIPTION
**Pull request by monsta**
fixes https://github.com/mate-desktop/mate-panel/issues/494

### CODE REVIEW

**Comment by raveit65** [comment]
...we have another open report, hopefully the fix helps here too.
https://github.com/mate-desktop/mate-panel/issues/555

**Comment by raveit65** [comment]
Ok, it seems that both issues are fixed with this commit.
echo "" >> /usr/share/applications/google-chrome.desktop
or 
yum-deprecated update / dnf update
are working fine now if ggz-gtk-client is installed.
I just tested this with mate-panel-1.19.0 / 1.18.2 and 1.16.2.
Looks like it is saved to back port it to 1.18/16.
Thanks

**Comment by monsta** [comment]
Oops, `gtk_drag_source_set_icon_gicon` doesn't exist in GTK+2. I'll have to correct the port to 1.16...

**Comment by raveit65** [comment]
@monsta 
We have a little remaining issue.
```
echo "" >> /usr/share/applications/google-chrome.desktop
```
generates this warning in .xsession-errors.
```
(mate-panel:7038): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
```
Same happens if you add the menubar to the panel.

**Pull request merged**
