### PR TITLE
Provide a fallback accessibility string for applets

### PR DESCRIPTION
**Pull request by johndescs**
Corresponds to https://github.com/mate-desktop/mate-panel/issues/835 and the thread beneath.

### CODE REVIEW

**Comment by alexarnaud** [comment]
Confirmed that it does what it promise to do.

**Comment by johndescs** [comment]
Pushed cosmetics enhancements after @cwendling's review.

**Comment by sthibaul** [comment]
Mmm.

Orca says so because it has panel role.
If the role is set to filler, does Orca still speak it when the applet is accessible? Does it speak it when the applet is not accessible?

If that other approach doesn't work, I'd tend to lean on your first option: having applets to overwrite the default description, or clear it if that's not the proper place to expose something.

**Comment by lukefromdc** [comment]
Is this going to get further work (to limit the fallback case to those applets don't provide a useful accessable string) or should we close this?

**Comment by alexarnaud** [comment]
@lukefromdc we don't plan to work on it again so I assume we can close this.

**Pull request closed without merging**
