### PR TITLE
Drop 'xau' from PKG_CHECK_MODULES call

### PR DESCRIPTION
**Pull request by wmww**
It appears this is no longer being used (if it ever was)

### CODE REVIEW

**Comment by raveit65** [comment]
How can we be sure that libXau.so or .Xauthority-files aren't used by the panel?
Btw. How did you check this in panel code?

You can also clean up build requires (libxau-dev) in https://github.com/mate-desktop/mate-panel/blob/master/.build.yml

**Comment by epgfm** [comment]
Looks like `libXau.so.6` was loaded by mate-panel `1.20.1-3ubuntu1`:
image

**Comment by wmww** [comment]
I checked by looking for a `Xauth.h` #include, or `xau`/`Xau` anywhere in the code.The only place those letters appear is here (plus a generated Makefile as a result of this). I'm assuming it was loaded because of the thing I removed (not because the panel was actually using it).

**Comment by raveit65** [comment]
@wmww 
Again, you can clean up build requires (libxau-dev) in https://github.com/mate-desktop/mate-panel/blob/master/.build.yml

**Comment by raveit65** [comment]
I old and obsolete 1.20 branch we have a more complex check in configure.ac but none includes in files.
```
[rave@mother mate-panel]$ grep -nr Xau *
configure.ac:189:  AC_CHECK_LIB(Xau, XauFileName,, AC_MSG_ERROR([libXau not found]))
configure.ac:193:  X_LIBS="$X_PRE_LIBS $X_LIBS -lX11 -lXau $X_EXTRA_LIBS"
[rave@mother mate-panel]$ grep -nr Xauth.h *
[rave@mother mate-panel]$ 
``` 
So it seems it was never really use before wayland port.

**Review by raveit65 — APPROVED** [review]
LGTM,
builds and runs fine under X11

**Comment by raveit65** [comment]
@wmww 
I will merge it when .build.yml is updated.

**Review by rbuj — APPROVED** [review]
LGTM. Legacy library,  see https://github.com/GNOME/gnome-panel/commit/f4e7e81152287d21a879993b631660f9ce9a3e45

**Pull request merged**
