### PR TITLE
notification_area: fix memory leak and move XAyatana(New)Label case at the bottom

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by raveit65** [comment]
@rbuj @lukefromdc @yetist 
Should i disable ArchLinux builds from travis CI ?
I have no idea why this currently happens and what is wrong with archlinux docker image.
We can always enable it again when some who his familiar with AL like to fix it.

**Comment by lukefromdc** [comment]
I would recommend doing than in general when one distro is getting Travis build failures that do not occur while actually building the package, as in this case:
```

>> [docker exec -t mate-panel-archlinux-build pacman -Syu --noconfirm] <<<

error: failed to initialize alpm library

(could not find or read directory: /var/lib/pacman/)
```
This clearly has nothing to do with what's actually in the commits

**Review by lukefromdc — COMMENTED** [review]
Builds without warnings, and the text label displays fine. Panel (tray built in-process) crashes however when killing the test program. Got this backtrace:
```

Thread 1 "mate-panel" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) thread apply all bt full


Thread 5 (Thread 0x7ffff12db700 (LWP 12136) "pool-mate-panel"):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007ffff714aab2 in g_cond_wait_until () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff70cc4e1 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff70ccac2 in g_async_queue_timeout_pop () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff7124009 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff71236bd in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007ffff7f5cea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737239693056, 8411626695087558253, 140737488346766, 140737488346767, 140737239690368, 8396800, -8411602933847486867, -8411609190355104147}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#7  0x00007ffff6c86def in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 4 (Thread 0x7ffff2422700 (LWP 12120) "dconf worker"):
#0  0x00007ffff6c7c3ff in __GI___poll (fds=0x5555557378d0, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
       sc_cancel_oldtype = 0
#1  0x00007ffff70fb6a6 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff70fb7af in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff35b738d in  () at /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
#4  0x00007ffff71236bd in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff7f5cea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737257809664, 8411626695087558253, 140737488347278, 140737488347279, 140737257806976, 8396800, -8411601031713845651, -8411609190355104147}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007ffff6c86def in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 3 (Thread 0x7ffff2cad700 (LWP 12119) "gdbus"):
#0  0x00007ffff6c7c3ff in __GI___poll (fds=0x5555556a4690, nfds=3, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
#1  0x00007ffff70fb6a6 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff70fb9eb in g_main_loop_run () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so
.0
#3  0x00007ffff7344896 in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x00007ffff71236bd in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff7f5cea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737266767616, 8411626695087558253, 140737488344590, 140737488344591, 140737266764928, 8396800, -8411602069485318547, -8411609190355104147}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007ffff6c86def in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7ffff34ae700 (LWP 12118) "gmain"):
#0  0x00007ffff6c7c3ff in __GI___poll (fds=0x555555690d60, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
#1  0x00007ffff70fb6a6 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff70fb7af in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff70fb801 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff71236bd in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff7f5cea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737275160320, 8411626695087558253
, 140737488344222, 140737488344223, 140737275157632, 8396800, -8411598770413564307, -8411609190355104147}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007ffff6c86def in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7ffff59e3f00 (LWP 12114) "mate-panel"):
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {0, 140737488344096, 140737488344100, 0, 1436842864, 2, 0, 2253092930260833792, 54, 140737247624150, 140737488344112, 140737488344032, 1, 2253092930260833792, 0, 140737247616024}}
        pid = <optimized out>
        tid = <optimized out>
#1  0x00007ffff6bae537 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0x2c00000000, sa_sigaction = 0x2c00000000}, sa_mask = {__val = {0, 140737488344032, 2253092930260833792, 4294967295, 0, 0, 0, 17, 0, 93824995232768, 93824996030480, 140737330543040, 140737247580520, 140737330872512, 8589934596, 64424509441}}, sa_flags = 0, sa_restorer = 0x100010101}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00007ffff6c07768 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff6d15e31 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
        ap = {{gp_offset = 24, fp_offset = 21845, overflow_arg_area = 0x7fffffffd5e0, reg_save_area = 0x7fffffffd570}}
        fd = <optimized out>
        list = <optimized out>
        nlist = <optimized out>
        cp = <optimized out>
#3  0x00007ffff6c0ea5a in malloc_printerr (str=str@entry=0x7ffff6d18110 "malloc_consolidate(): invalid chunk size") at malloc.c:5347
#4  0x00007ffff6c0f918 in malloc_consolidate (av=av@entry=0x7ffff6d47b80 <main_arena>) at malloc.c:4477
        idx = <optimized out>
        fb = 0x7ffff6d47b90 <main_arena+16>
        maxfb = 0x7ffff6d47bd8 <main_arena+88>
        p = 0x7ffff6d47be0 <main_arena+96>
        nextp = <optimized out>
        unsorted_bin = 0x7ffff6d47be0 <main_arena+96>
        first_unsorted = <optimized out>
        nextchunk = <optimized out>
        size = <optimized out>
        nextsize = <optimized out>
        prevsize = <optimized out>
        nextinuse = <optimized out>
#5  0x00007ffff6c11755 in _int_malloc (av=av@entry=0x7ffff6d47b80 <main_arena>, bytes=bytes@entry=1280) at malloc.c:3699
        nb = 1296
        idx = 68
        bin = <optimized out>
        victim = <optimized out>
        size = <optimized out>
        victim_index = <optimized out>
        remainder = <optimized out>
        remainder_size = <optimized out>
        block = <optimized out>
        bit = <optimized out>
        map = <optimized out>
        fwd = <optimized out>
        bck = <optimized out>
        tcache_unsorted_count = <optimized out>
        tcache_nb = <optimized out>
        tc_idx = <optimized out>
        return_cached = <optimized out>
        __PRETTY_FUNCTION__ = "_int_malloc"
#6  0x00007ffff6c13299 in __GI___libc_malloc (bytes=1280) at malloc.c:3066
        ar_ptr = 0x7ffff6d47b80 <main_arena>
        victim = <optimized out>
        hook = <optimized out>
        tbytes = <optimized out>
        __PRETTY_FUNCTION__ = "__libc_malloc"
#7  0x00007ffff71011a8 in g_realloc () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#8  0x00007ffff75b3914 in pango_glyph_string_set_size () at /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0
#9  0x00007ffff75cf095 in  () at /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0
#10 0x00007ffff75ce66f in pango_shape_with_flags () at /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0
#11 0x00007ffff75ceadb in pango_shape_full () at /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0
#12 0x00007ffff75b93fd in pango_context_get_metrics () at /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0
#13 0x00005555555b1feb in  ()
#14 0x00005555555b26a1 in  ()
#15 0x00005555555b2ae0 in  ()
#16 0x00005555555b4916 in  ()
#17 0x00005555555b4a30 in  ()
#18 0x00007ffff79a54d3 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#19 0x00007ffff79a5fa5 in gtk_widget_get_preferred_height_and_baseline_for_width () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#20 0x00007ffff79a6053 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#21 0x00005555555b4812 in  ()
#22 0x00007ffff71ea18e in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#23 0x00007ffff7201ffe in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#24 0x00007ffff72021e2 in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#25 0x00007ffff7819148 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#6  0x00007ffff6c13299 in __GI___libc_malloc (bytes=1280) at malloc.c:3066
        ar_ptr = 0x7ffff6d47b80 <main_arena>
        victim = <optimized out>
        hook = <optimized out>
        tbytes = <optimized out>
        __PRETTY_FUNCTION__ = "__libc_malloc"
#7  0x00007ffff71011a8 in g_realloc () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#8  0x00007ffff75b3914 in pango_glyph_string_set_size () at /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0
#9  0x00007ffff75cf095 in  () at /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0
#10 0x00007ffff75ce66f in pango_shape_with_flags () at /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0
#11 0x00007ffff75ceadb in pango_shape_full () at /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0
#12 0x00007ffff75b93fd in pango_context_get_metrics () at /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0
#13 0x00005555555b1feb in  ()
#14 0x00005555555b26a1 in  ()
#15 0x00005555555b2ae0 in  ()
#16 0x00005555555b4916 in  ()
#17 0x00005555555b4a30 in  ()
#18 0x00007ffff79a54d3 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#19 0x00007ffff79a5fa5 in gtk_widget_get_preferred_height_and_baseline_for_width () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#20 0x00007ffff79a6053 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#21 0x00005555555b4812 in  ()
#22 0x00007ffff71ea18e in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#23 0x00007ffff7201ffe in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#24 0x00007ffff72021e2 in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#25 0x00007ffff7819148 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
--Type <RET> for more, q to quit, c to continue without paging--
#26 0x00007ffff71ea18e in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#27 0x00007ffff7201ffe in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#28 0x00007ffff72021e2 in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#29 0x00007ffff7630c07 in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#30 0x00007ffff761cca9 in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#31 0x00007ffff70fbed4 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#32 0x00007ffff70fb38f in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#33 0x00007ffff70fb708 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#34 0x00007ffff70fb9eb in g_main_loop_run () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#35 0x00007ffff78fcc95 in gtk_main () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#36 0x0000555555579118 in main ()
```

**Comment by rbuj** [comment]
The segfault produced by the SIGABRT signal should be fixed now.

**Review by lukefromdc — APPROVED** [review]
This now seems to work perfectly, the segfault and crash on killing the test application is gone. Also no build warnings from these files. Looks good to go

**Comment by lukefromdc** [comment]
The travis problems have nothing to do with the contents of this PR: 
one is a rate limiter and the other is
```
error: failed to initialize alpm library

(could not find or read directory: /var/lib/pacman/)
```

**Review by raveit65 — APPROVED** [review]
LGTM

**Comment by rbuj** [comment]
> I would recommend doing than in general when one distro is getting Travis build failures that do not occur while actually building the package, as in this case:
> 
> ```
> 
> >> [docker exec -t mate-panel-archlinux-build pacman -Syu --noconfirm] <<<
> 
> error: failed to initialize alpm library
> 
> (could not find or read directory: /var/lib/pacman/)
> ```
> 
> This clearly has nothing to do with what's actually in the commits

It seems it's because of [glibc](https://www.reddit.com/r/archlinux/comments/lek2ba/arch_linux_on_docker_ci_could_not_find_or_read/gmziv8m/?utm_source=reddit&utm_medium=web2x&context=3)

**Pull request merged**
