### PR TITLE
GTK 3.22: Avoid deprecated gtk_menu_popup

### PR DESCRIPTION
**Pull request by lukefromdc**
Port to gtk_menu_popup_at_widget and when that cannot be used gtk_menu_popup_at_pointer.

### CODE REVIEW

**Comment by lukefromdc** [comment]
One behavior change resulted: the context menu for the main menubar now follows the pointer where previously it aligned with the left hand edge of the entire menubar. Trying to get the widget in mate-panel-applet.c for this caused the context menu for the main menubar and only the main menubar to come up far out of position, well to the right. Apparently the widget here is the entire panel, so pointer has to be used unless we want to get fancy and find the rectangle occupied by the main menubar and attach the context menu to that,

**Comment by lukefromdc** [comment]
An attempt to use gtk_menu_popup_at_widget for the panel main menubar right-click menu did not work unless the menu was all the way to the left. It worked then and only then, otherwise the context menu was rendered too far right (or down for vertical panel), and the farther the applet was from the left or top the worse the problem.  When it did work, aligning the context menu with the left edge of the menubar was less natural than positioning it to the pointer, due to the width of the menubar. 

When right-clicking "system" the behavior with gtk_menu_popup_at_pointer puts the context menu close to the original location,  while aligning it with the far left edge of the menubar looked odd. Anyway, the experimental code exists on another branch at
https://github.com/mate-desktop/mate-panel/tree/dev-menu-popup-experimental
I excluded it from this PR as it not only is not ready but did not look as good when it did work. The branch is there though if anyone wants to play with it

**Comment by raveit65** [comment]
First, the deprecation fix doesn't solve https://github.com/mate-desktop/mate-panel/issues/653
Any way, we should fix the deprecation.
I didn't test the experimental branch yet. but using gtk_menu_popup_at_pointer for the menubar looks OK for me.
Only if the menubar is at the right edge of the monitor, than the right-click-context-menu pops up on the left side of the pointer, which looks a bit weird if you click on the application menu.
The application-menu isn't at the monitor edge in this case. It seems to be a new behaviour with the new functions that the context-menu pops up on the other side of the pointer if there isn't enough space.
But i think this is a rare case and i don't know a layout for it. I never heard about a *RTL* layout.

Can we try to use gtk_menu_popup_at_pointer also for the work-space-switcher, if it's possible to use it only for this wnck-applet?
I am using 8 workspaces in one row and and if you click on the right side of the applet with the pointer, the context-menu pops up on the left side, which looks weird.

**Comment by raveit65** [comment]
Ok, i just tested experimental branch.
For me using gtk_menu_popup_at_pointer for the menubar context-menu looks better.
Only for the rare case that the menubar is on the right side of the monitor it seems a better alternative.

**Comment by lukefromdc** [comment]
Rebased after https://github.com/mate-desktop/mate-panel/commit/8a158fe4fba20e89a055e304357db68111a45422

**Comment by lukefromdc** [comment]
I just found that using gtk_menu_popup_at_pointer for the wncklet/switcher does not work, because that is mate-panel-applet.c and then does not work for the tray. The tray menu only pops up on the handle, and gtk_menu_popup_at_pointer apparently calls gtk_menu_popup_at_rect within GTK and I get this error when trying to open the tray context menu:

`(mate-panel:14881): Gtk-CRITICAL **: gtk_menu_popup_at_rect: assertion 'GDK_IS_WINDOW (rect_window)' failed`

That same tray context menu works fine with gtk_menu_popup_at_widget, at the expense that a long switcher is going to align the menu with the left edge

**Comment by lukefromdc** [comment]
gtk_menu_popup_at_pointer also does not work for the window list context menu, returning the exact same error.It works on the switcher quite nicely, but fails whenever it is called with the pointer on a handle.

 Apparently gtk_menu_popup_at_pointer invoked the same invalid window issue for gtk_menu_popup_at_rect within GTK anytime it's called on a pointer over a handle in mate-panel

**Comment by raveit65** [comment]
Hmm, maybe we leave that for the future if we ever will switch to wayland or gtk+4 ?
No need to delete the branch in that case.
Still wondering how this will handle with gnome-panel as switch to gtk+-4 and x-wayland will be earlier....

**Comment by raveit65** [comment]
At least all this new stuff isn't mark as stable in gtk docs.

**Comment by lukefromdc** [comment]
We've already got several other deprecations that cannot be easily fixed, such as the deal with reparenting a moved applet and the actiongroup stuff that removes icons from menus if it is "fixed." We didn't get any advantage from fixing this one, and mate-panel cannot now run in Wayland due to direct dependencies on X and bugs in xwayland

**Comment by lukefromdc** [comment]
Maybe we just wait for whatever gnome-paned does and copy it?

**Comment by lukefromdc** [comment]
Closing this. leaving branch: we get no advantages and a visual issue in at least one use case

**Comment by raveit65** [comment]
yeah, let's wait, it isn't urgent.

**Comment by raveit65** [comment]
For the record, i think we can't use gtk_menu_popup_at_pointer for the panel as we support keyboard navigation.
I tried to use *gtk_menu_popup_at_pointer* for volume-applet as GtkStatusIcon isn't a widget.
So i couldn't use *gtk_menu_popup_at_widget* here.
The result was that the right-click menu pops up where the pointer is, possible at another place of the monitor. So this breaks keyboard navigation.
For me this new gtk functions isn't really smart outside of gnome-(s)hell.

**Comment by lukefromdc** [comment]
This, in turn means that a port to Wayland that supports keyboard navigation will need gtk_menu_popup_at_rect and a location function to calculate where that rectangle should be.  The existing (deprecated) function apparently has issues in wayland with positioning.

**Pull request closed without merging**
