### PR TITLE
Fixing damaged clock image

### PR DESCRIPTION
**Pull request by raveit65**
Fixes https://github.com/mate-desktop/mate-panel/issues/520
Tested with master for gtk+-3.22 and 1.18 branch for gtk+-3.22 and 3.14
Please test.

### CODE REVIEW

**Comment by lukefromdc** [comment]
Merged with 
https://github.com/mate-desktop/mate-panel/commit/69f396b25e993e04fe7efcdb8ff99c687d14d568
and
https://github.com/mate-desktop/mate-panel/commit/4de86661f4a6f67285333c67342c287f99deffeb

**Comment by monsta** [comment]
Guys, does the second commit affect anything? I just wonder whether it might be needed in 1.18 branch or not.

**Comment by lukefromdc** [comment]
I never tested them separately,but  the second commit removes unneeded code at the least.  The function removed is said not to work anymore so premumably it should not be used. Bringing it back when applying this to 1.18 would be a potential source of a bug it seems. At the very least it would require new testing to split it up.

**Comment by raveit65** [comment]
clock: drop deprecated gtk_size_group_set_ignore_hidden
isn't needed to fix the issue, For some reasons i didn't seperate it in PR.
But take a look at https://developer.gnome.org/gtk3/stable/GtkSizeGroup.html#gtk-size-group-set-ignore-hidden.
This function is deprecated with 3.20 and it seems that it doesn't work with older gtk+.
I use this commit as patch in fedora with 1.18.x already.
So i am +1 for adding this to 1.18.

**Comment by raveit65** [comment]
Btw. it is dropped from gnome-panel too.

**Comment by monsta** [comment]
Ok, done in https://github.com/mate-desktop/mate-panel/commit/15f2b5650b00e947e49121bf9e9f31ffe9de4343.

**Comment by ekotoyants** [comment]
There is still [problem](https://kotoyants.com/public/img_20170620105521.gif) with this applet.

**Comment by lukefromdc** [comment]
That's not a problem with the analog clock image, it's the "set" button taking too much space and stretching the entire calendar window popup. I just tested for this with GTK 3.22.15 and every theme I have (including all the MATE themes) and could not duplicate it. What version of mate-panel, and what version of GTK 3?

**Comment by ekotoyants** [comment]
Did you configure a location that has different week day like in example (there is Monday in Kahului when there is Tuesday in Odessa - 13 Hours Time Difference)?

Arch Linux
gtk3 3.22.16-1
mate-panel 1.18.3-1
BlueMenta Theme

**Comment by monsta** [comment]
Took me a while to find the existing report about this new issue. It was reported in the wrong repo: https://github.com/mate-desktop/mate-applets/issues/101.

**Comment by raveit65** [comment]
I added Odesa and Kahului location (my home is berlin), and use Odesa at home location.
Hovering with the mouse over the edit button of Kahului does not produce any failure here.
I can't reproduce it with BlueMenta.
@ekotoyants 
Are you sure this is BlueMenta?
The button style doesn't look like BlueMenta, maybe Adwaita or Arc-theme?
Which version of mate-themes?
I suggest to open an new report at mate-panel for this.

**Comment by ekotoyants** [comment]
Sorry my fault, I am using customized BlueMenta with "Controls" Clearlooks and "Icons" Faenza.

**Comment by raveit65** [comment]
A customized BlueMenta.......
Than you have a error with handling the border of the button for different button states.
.... a so called jumping button.
To be sure can you test origin BlueMenta from last release for gtk+-3.22, please?
http://pub.mate-desktop.org/releases/themes/3.22/mate-themes-3.22.12.tar.xz
You can simply copy the Bluementa theme folder to /usr/share/themes/ and reload the theme.
And move your custom theme first to another dir.

**Comment by monsta** [comment]
Kahului is already 06:01 at the moment, meaning it's the same day (Wednesday), so the line isn't long enough to trigger the issue.

**Comment by raveit65** [comment]
Ok, adding Brisbane (Thuesday in Australia) trigger the issue here.
@ekotoyants 
Can you please open a new report for it?
Sorry, we can't move the existing report from mate-applets to mate-panel at github.
...than i can confirm the issue.

**Comment by ekotoyants** [comment]
[Screen](https://kotoyants.com/public/img_20170622100616.gif) with BlueMenta and DualScreen (tested on both single and dual screen).

**Comment by ekotoyants** [comment]
Should I open a new report in mate-panel? What about [mate-applets#101](https://github.com/mate-desktop/mate-applets/issues/101)? It is still open won't it be a duplicate report?

**Comment by raveit65** [comment]
Yes, please at mate-panel, than we can close the other one which is at the wrong place.

**Comment by ekotoyants** [comment]
[mate-panel#594](https://github.com/mate-desktop/mate-panel/issues/594)

**Pull request closed without merging**
