### PR TITLE
Reenable workspace switcher applet wrapping behavior

### PR DESCRIPTION
**Pull request by muesli4**
See https://github.com/mate-desktop/mate-panel/issues/420. (Note: I accidentally rebased, but that shouldn't be a big deal.)

### CODE REVIEW

**Comment by raveit65** [comment]
hmm, the PR does not fix it here.
I can't enable wrap via applet gui but i got a new build warning
```
workspace-switcher.c: In function 'applet_scroll':
workspace-switcher.c:240:3: warning: enumeration value 'GDK_SCROLL_SMOOTH' not handled in switch [-Wswitch]
   switch (event->direction)
   ^~~~~~
```

**Comment by muesli4** [comment]
It works perfectly fine on my machine, I built a package and used it since then.

For the warning: That case is missing in the handler, however not in the WnckPager applet. I already created a patch for *libwnck* (see https://bugzilla.gnome.org/show_bug.cgi?id=780490) to share that functionality. Then I would create another patch for *mate-panel* to make use of it (which would then fix all compiler warning). Sadly, getting your code in is a slow process.

**Comment by monsta** [comment]
Second ```switch``` that starts at line 254 doesn't handle ```GDK_SCROLL_SMOOTH``` as well, but here it's not so harmless. There's an assertion in the ```default```.

**Comment by raveit65** [comment]
OK, my fault , i miss read your PR and bugreport. The function is only working with mousescrolling again but does not have any influence on keyboard settings for it.
```
org.mate.Marco.general wrap-style
```
crtl+alt+left/right

**Comment by monsta** [comment]
Funny code in libwnck... so they added smooth scrolling support in:
https://git.gnome.org/browse/libwnck/commit/?id=82f4f0985d7ddb41bd3f4ddd1398ce37a88308f9

But they already had this change at the moment:
https://git.gnome.org/browse/libwnck/commit/?id=de74b83bfdb78af536e71c58fc297a1eb3b7efe0

This stays in their code up to this day, so I guess we could add the same dummy handling here. Not sure if ```GDK_SCROLL_SMOOTH``` could ever reach this function, but I prefer to have some protection against unexpected values.

**Comment by lukefromdc** [comment]
Merged with
https://github.com/mate-desktop/mate-panel/commit/9b8f9e8147e27e19eb08a262a140b937051545b9

**Comment by raveit65** [comment]
@monsta 
I recall that we use such a 'dummy handling' somewhere in code.
Can you please add this?
No need to introduce a warning.
@muesli4 
I maintain libwnck in fedora.
@muktupavels 
Can you please take a look at https://bugzilla.gnome.org/show_bug.cgi?id=780490  ?

**Comment by muktupavels** [comment]
@raveit65 you want contact Marco Trevisan, he is libwnck maintainer. I added small review about style / indentation. Otherwise patch looks good, I have nothing against it.

**Comment by lukefromdc** [comment]
OK, as of the moment the functionality works at the price of introducing the warning. The proposed patch for libwnck will stop the warning. If it is not merged, do we want to revert this here or keep the functionality and leave the warning? I would vote for the latter, and for trying to find a way to trap the unhandled call within mate-panel.

**Comment by muktupavels** [comment]
What warning? from where?

**Comment by lukefromdc** [comment]
Raveit got this warning:
```

workspace-switcher.c: In function 'applet_scroll':
workspace-switcher.c:240:3: warning: enumeration value 'GDK_SCROLL_SMOOTH' not handled in switch [-Wswitch]
   switch (event->direction)
```

**Comment by muktupavels** [comment]
Add empty case and no more warning, easy no?
If that should not be reached than add also assert.
Or just add code that does something?

libwnck returns FALSE in that case so empty case should be enough to fix warning. I guess real question here is why libwnck returns FALSE for GDK_SCROLL_SMOOTH and then later in switch tries to handle that which will be never reached.

**Comment by muesli4** [comment]
@raveit65 The workspace switcher applet from *mate-panel* and *marco* both use the `WnckPager` widget. However the issue at hand is only related to *mate-panel*.

@muktupavels The thing is that *libwnck* already provides a handler which handles the `GDK_SCROLL_SMOOTH` case. See variable `absolute_direction` where it either gets `GDK_SCROLL_LEFT` or `GDK_SCROLL_RIGHT`. Once I get my code into *libwnck* this missing case should no longer matter. Thanks for reviewing by the way.

**Comment by monsta** [comment]
Hmm... are we in a hurry? I would prefer the merge happen only after addressing all the issues. Oh well, I'll fix it in master then.

**Comment by monsta** [comment]
Ok, https://github.com/mate-desktop/mate-panel/commit/9705869fdcf0f31bc05b8454cd7ec60b7b489234 should do it.

**Comment by raveit65** [comment]
I can confirm that https://github.com/mate-desktop/mate-panel/commit/9705869fdcf0f31bc05b8454cd7ec60b7b489234 fixes the build warning.

**Comment by lukefromdc** [comment]
I originally merged this just before the build warning was posted here, having missed that myself. PR functioned and had been approved by another, so I went ahead with it. Thanks for cleaning up the warning

**Pull request closed without merging**
