### PR TITLE
avoid deprecated gdk_screen_get_width/height

### PR DESCRIPTION
**Pull request by sc0w**

### CODE REVIEW

**Comment by lukefromdc** [comment]
Seems to work fine here, tested fish, calendar popup positioning, and menus. Fish and clock tested built in-process as per my usual builts.

**Comment by raveit65** [comment]
This is a huge PR, I am just testing.

**Comment by lukefromdc** [comment]
Also does not in any way interfere with a later merge of my in-process work, a test branch merged both PR's cleanly. This may be a big PR but it won't make extra merge work for me later.

**Comment by lukefromdc** [comment]
Rebased and merged with https://github.com/mate-desktop/mate-panel/commit/7b2bc7d9f98c6ba8c2c31bdf9605faadb42a7e0e

**Pull request closed without merging**
