### PR TITLE
workspace-switcher: provide themed fallback color

### LINKED ISSUE #807: Workspace switcher: with HighContrast theme, no way to determine the current workspace
#### Expected behaviour
Current desktop should be distinguishable by a visual effect

#### Actual behaviour
There is no way to determine the currently selected workspace.

capture du 2018-05-09 14-33-40

#### Steps to reproduce the behaviour
1) Select the GNOME High Contrast theme
2) Open Pluma on the workspace 1, maximize the Pluma window
3) Open Mate terminal on the workspace 2, maximize the Mate terminal window

#### MATE general version
1.20.1

#### Package version
1.20.1-3

#### Linux Distribution
Debian Sid

### PR DESCRIPTION
**Pull request by vkareh**
When a theme does not specify a color for the highlighted workspace, we can look it up from the current theme and provide that as a fallback color.

Fixes #807

### CODE REVIEW

**Comment by lukefromdc** [comment]
Here is mate-panel with this PR, compiz, an overlapping window on an adjacent desktop, and HichContrast
workspace_switcher_w_pr_and_highcontrast

**Comment by lukefromdc** [comment]
The other themes looked fine, the code itself seems to work fine.

**Comment by vkareh** [comment]
Okay, I'll see if I can add a contrasting border color

**Comment by vkareh** [comment]
@lukefromdc - I cannot add a border color, as HighContrast already adds a black border. The real issue is that they don't provide a contrasting color by default, which is ironic given the theme name. This sets the fallback to do just that, but the border gets lost in there... The proper solution is to change the GTK theme directly. I'll work on a patch for that, but this should improve accessibility in the meantime.

@alexarnaud - does this explanation above make sense? Is this an acceptable solution for now? (see @lukefromdc's screenshot above)

Also to note that the HighContrast theme uses the Adwaita icon set by default, rather than the HighContrast icon set... this should also be addressed, of course.

**Comment by lukefromdc** [comment]
I'm not the one who should decide this, we need to know what works for those with visual impairments or working in bright sun with dim laptop screens

**Comment by raveit65** [comment]
Isn't possible to add the border only for some specific themes and using GTK_STYLE_PROVIDER_PRIORITY_APPLICATION to override the wrong border-color from gtk+ themes?
See what @lukefromdc did for xrandr-applet.
https://github.com/mate-desktop/mate-settings-daemon/blob/master/plugins/xrandr/msd-xrandr-manager.c#L1848
and
https://github.com/mate-desktop/mate-settings-daemon/blob/master/plugins/xrandr/msd-xrandr-manager.c#L1868

Personal i would prefer to add a border only for themes where it is needed.
Our own themes don't need that.

**Comment by lukefromdc** [comment]
@vkareh says HighContrast already sets a black border. We could override that in HighContrast and maybe HighContrastInverse only

**Comment by vkareh** [comment]
Hmmm... At that point we could very well remove this entire chunk of code and have mate's own HighContrast add the missing styling

**Comment by alexarnaud** [comment]
Le 31/05/2018 à 22:57, Victor Kareh a écrit :
> @alexarnaud <https://github.com/alexarnaud> - does this explanation 
> above make sense? Is this an acceptable solution for now? (see 
> @lukefromdc <https://github.com/lukefromdc>'s screenshot above)

It looks good to me.

> Also to note that the HighContrast theme uses the Adwaita icon set by 
> default, rather than the HighContrast icon set... this should also be 
> addressed, of course.

It has been recently solved: 
https://github.com/mate-desktop/mate-themes/commit/becf3ea2f1ce8b43bd628c9d9c7af9aa9e97fd1b

Best regards,
Alex.

**Comment by lukefromdc** [comment]
If this is OK for  @alexarnaud than it's good enough for me. I prefer in accessability questions to defer to the judgement of those who are directly affected.

**Comment by raveit65** [comment]
HC theme looks OK for me with fedora 28.
wnck-switcher-hc
Other gtk+ themes are fine too, and our themes use their own styling.

**Comment by alexarnaud** [comment]
@raveit65 @vkareh Do you think we could backport this fix for 1.20 ?

Best regards,
Alex.

**Comment by vkareh** [comment]
Yes, this fixes an existing bug, so we should definitely backport this

**Pull request merged**
