### PR TITLE
panel-run-dialog.ui: avoid deprecated:

### PR DESCRIPTION
**Pull request by sc0w**
avoid deprecated:

GtkVBox
GtkHbox
GtkImage:stock
GtkButton:use-stock

### CODE REVIEW

**Comment by lukefromdc** [comment]
Rebased and merged with
https://github.com/mate-desktop/mate-panel/commit/4d84a7e7881cfd3b02ef36b443661f5f333efbf7

**Comment by lukefromdc** [comment]
Whoops: had to revert this for now! The panel run dialog looked exactly the same, and you could go through the program list and all-but the caret to enter text would not show up and a program name could not by type. Made a new branch containing the existing commit, pushed it as panel-run-dialog.ui again, and reverted in master until it is fixed.

**Comment by sc0w** [comment]
I don't know how to show the run dialog, how to do it step by step?

btw, I see you reverted the wrong commit:

> lukefromdc Revert "panel-test-applets.ui: avoid deprecated:

**Comment by lukefromdc** [comment]
Just fixed that,reverted the revert and then reverted the right commit. Sorry about the churn, I am tired and got a bit frantic. Run dialog now works again in master, not going to try to squash and get rid of those as that breaks local repos. To show the run dialog, the alt-F2 key combination will bring it up, and also there is a "run application" applet for the panel

**Comment by sc0w** [comment]
ok, fixed in https://github.com/mate-desktop/mate-panel/pull/776

@lukefromdc please test

**Pull request closed without merging**
