### PR TITLE
Update workspace switcher properties dialog

### PR DESCRIPTION
**Pull request by muesli4**
Removed deprecated ui elements to make it fully compatible with GTK+ 3
and additionally made the dialog resizeable.

### CODE REVIEW

**Comment by muesli4** [comment]
Fixes https://github.com/mate-desktop/mate-panel/issues/687.

Also makes some minor cosmetic changes (but nothing big, only for consistency). (Can be tested by replacing just the ui file.)

**Comment by lukefromdc** [comment]
workspace-switcher_ui

**Comment by muesli4** [comment]
Thanks for testing it. I fixed it (by adding the missing group). (I amended to the last commit.)

**Comment by sc0w** [comment]
beforelaterpr

without the PR (left) / with the PR (right)

and now resizable, looks ok for me

**Pull request merged**
