### PR TITLE
Update org.mate.panel.object schema descriptions

### LINKED ISSUE #1132: Panel objects schema inaccurate
#### Expected behaviour
action-type key for panel object in schema should provide accurate description and enumerated list of available actions.

#### Actual behaviour
Enumerated list includes 'last' and 'suspend' which don't appear to be handled in the source code. In addition, the schema description for the action-type key states "Possible values are "lock", "logout", "run", "search" and "screenshot"", which is incomplete and inaccurate.

#### Steps to reproduce the behaviour
Navigate to an object using dconf-editor (org.mate.panel.objects._object_), select the action-type key.

#### MATE general version
1.24.0

#### Package version
mate-panel 1.24.0-2

#### Linux Distribution
Linux Mint 20 MATE

#### Link to downstream report of your Distribution
None.

#### Notes
My apologies that this Issue is phrased in terms of dconf-editor and not the schema itself, but I don't know where the schema is located. Given that dconf-editor derives its data from the mate-panel provided schema, I am hoping that this will be sufficient to pinpoint the inaccuracies in the schema. Many thanks.

### PR DESCRIPTION
**Pull request by cwendling**
It was listing outdated values, and missing new ones.

Fixes #1132.

### CODE REVIEW

**Review by zhuyaliang — APPROVED** [review]
Panel objects schema is more complete and accurate

**Review by lukefromdc — APPROVED** [review]
Looks good to me. More readable, and as expected with just description changes identical panel behavior with this installed.

**Comment by lukefromdc** [comment]
Would be good to get another review as the older version of dconf-editor I use doesn't find the panel objects schema at all.

**Comment by cwendling** [comment]
@lukefromdc you can also show the schema description using `gsettings describe`:

```console
$ gsettings describe org.mate.panel.object:/org/mate/panel/objects/notification-area/ action-type
The action type this button represents. Possible values are 'none', 'lock', 'logout', 'run', 'search', 'force-quit', 'connect-server' and 'shutdown'. This key is only relevant if the object-type key is 'action'.
```

**Comment by lukefromdc** [comment]
The action type this button represents. Possible values are 'none', 'lock', 'logout', 'run', 'search', 'force-quit', 'connect-server' and 'shutdown'. This key is only relevant if the object-type key is 'action'.

**Pull request merged**
