### PR TITLE
Avoid deprecated g_type_class_add_private

### PR DESCRIPTION
**Pull request by yetist**
Avoid deprecated g_type_class_add_private under `libmate-panel-applet` and `mate-panel` directories.

### CODE REVIEW

**Comment by sc0w** [comment]
I noticed this cppcheck warning:

`[libmate-panel-applet/mate-panel-applet.c:56]: (style) struct member '_MatePanelAppletPrivate::applet' is never used.`

**Comment by raveit65** [comment]
Second commit gives me a segfault (ignore dbind-warning)
```
[rave@mother ~]$ mate-panel --replace

(mate-panel:13712): dbind-WARNING **: 17:48:31.113: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
Segmentation fault (core dumped)
[rave@mother ~]$
```

First commit seems OK.

**Comment by yetist** [comment]
@raveit65 

Pushed a new commit, please test again, thank you.

**Comment by raveit65** [comment]
@yetist 
This works now an panel starts well :)
I'd like to test this PR a bit more as the is a huge commit.

**Comment by lukefromdc** [comment]
I can see in the new commit what probably caused the segfault so we should be done with that. testing now...

**Comment by lukefromdc** [comment]
Is this ready to go or is more testing needed on account of its size?

**Comment by sc0w** [comment]
@lukefromdc 

@raveit65 said:

> I'd like to test this PR a bit more as the is a huge commit.

I think we can wait his review

**Comment by lukefromdc** [comment]
No sweat, just needed to know

**Comment by sc0w** [comment]
@yetist latest commit can be squashed into first commit?

**Comment by yetist** [comment]
@sc0w 

Done, rebase and squash the last commit into the previous one.

**Pull request merged**
