### PR TITLE
don't use excessive string duplication

### PR DESCRIPTION
**Pull request by sc0w**
@monsta you did the same in https://github.com/mate-desktop/caja-extensions/commit/5fa187fd69c9a352bae38cbced4120dc942fc7a6

please test

### CODE REVIEW

**Comment by sc0w** [comment]
I see the warning:

> panel-run-dialog.c:412:5: warning: passing argument 6 of ‘g_spawn_async’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
>      display_name,

I am not sure, so, I decide to close this PR

**Comment by monsta** [comment]
Hmm, `g_spawn_async` doesn't accept const pointer for that argument.

**Comment by raveit65** [comment]
@monsta 
Should i merge existing similar PRs like they are?
With
**display_name = g_strdup (gdk_display_get_name (display));**

**Comment by monsta** [comment]
It doesn't hurt, just a bit more memory allocation.

**Comment by lukefromdc** [comment]
Using a few extra bytes of RAM is preferable to a few extra warnings or especially actual bugs that users would notice.

**Pull request closed without merging**
