### PR TITLE
Fix run dialog show-program-list enabling

### LINKED ISSUE #296: Run Application dialog: wrong reaction to show-program-list enabling
Steps to reproduce:
1. Have show-program-list property in org.mate.panel schema turned off.
2. Press Alt-F2 to invoke Run Application dialog. The program list will be hidden.
3. Enable show-program-list via dconf-editor.
4. See the empty space instead of the program list:

run-dialog-wrong

It should be:

run-dialog-right

Tested in MATE 1.8 on two systems - LMDE 2 "Betsy" and Ubuntu MATE 15.04.

**Note:** this is not related to the known GLib 2.43 issue.
## 

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/11267691-run-application-dialog-wrong-reaction-to-show-program-list-enabling?utm_campaign=plugin&utm_content=tracker%2F314880&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F314880&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by info-cppsp**
fix  #296

### CODE REVIEW

**Comment by info-cppsp** [comment]
The whole thing feels utterly stupid to me.
Please give me a reason WHY??? someone would do this.

**Comment by raveit65** [comment]
I have no idea about what you talking about....
Everybody see what you post and all team member gets email notification about.

**Comment by lukefromdc** [comment]
Rebased and merged with https://github.com/mate-desktop/mate-panel/commit/f20f4b9e45c1ac33e651fdd77ccf8a530c894d73

**Comment by info-cppsp** [comment]
^ The feature for which this PR is a bugfix seems pretty useless to me.
Not only that, but its [implementation](https://github.com/mate-desktop/mate-panel/issues/296#issuecomment-361954413) seems to be a bad design.
But I guess I'm the only one...

**Comment by monsta** [comment]
Weird... now the dialog doesn't become resizable after I enable the program list manually (by clicking on expander). It expands normally, but I can't resize it. Can anyone confirm this?

**Comment by alexarnaud** [comment]
Le 18/03/2018 à 16:52, monsta a écrit :
> Weird... now the dialog doesn't become resizable after I enable the 
> program list manually (by clicking on expander). It expands normally, 
> but I can't resize it. Can anyone confirm this?

I can confirm the exact inverse behavior. On my Mate 1.8, when I close 
the application list, I cannot resize the run dialog.

Best regards,
Alex.

**Comment by info-cppsp** [comment]
@monsta 
please review the fix for the fix...

**Comment by monsta** [comment]
@alexarnaud: that's the usual behavior... and you'd get the same without this PR.

**Comment by monsta** [comment]
@info-cppsp: thanks, it works, merged.

**Pull request closed without merging**
