### PR TITLE
struts: add support for _GNOME_WM_STRUT_AREA

### PR DESCRIPTION
**Pull request by rbuj**
See #1229

### CODE REVIEW

**Review by lukefromdc — COMMENTED** [review]
A test build finished and ran without any surprises. On testing struts on marco with a 4K monitor, I didn't get any gaps with fullscreened or tiled windows. With one monitor running and one panel on each edge of the screen, all the panel edges butted against edges of fullscreened or tiled windows.

I then tested two panels one next to the other on one edge, windows always maximized or tiled partway under the inner panel. Note that years ago on 1280x1024 monitors I used to run two bottom panels one on top the other.

Finally I tested with both monitors running and 8 panels one at each screen edge. All of them worked as expected except the right edge of the left (primary) monitor. This panel got windows maximizing/tiling under it far enough to reach the close button.

Struts between monitors don't work at all with compiz as it does not support this. Struts for panels on all four edges of a single screen worked fine with compiz however.

**Comment by raveit65** [comment]
GNOME_WM_STRUT_AREA was introduced to fix
#303
#803
mate-desktop/marco/issues/135
But this PR doesn't solve the problems.
A Window always maximize under bottom panel when using 2 monitors arranged vertical with HIDPI.
This works well with using gnome-panel, so i am in doubt that GNOME_WM_STRUT_AREA is respected.
More details about to test or debug the issue you can find here https://github.com/mate-desktop/mate-panel/pull/1229

**Comment by raveit65** [comment]
I got same wrong results like posted with PR of mine.
https://github.com/mate-desktop/mate-panel/pull/1229#issuecomment-850837075
Results of `xprop | grep _WM_STRUT` for top/bottom/left panel (in this order).
```
[rave@mother ~]$ xprop | grep _WM_STRUT
_GNOME_WM_STRUT_AREA(CARDINAL) = 0, 0, 3790, 50
_NET_WM_STRUT_PARTIAL(CARDINAL) = 0, 0, 51, 0, 0, 0, 0, 0, 0, 3838, 0, 0
_NET_WM_STRUT(CARDINAL) = 0, 0, 51, 0
[rave@mother ~]$ xprop | grep _WM_STRUT
_GNOME_WM_STRUT_AREA(CARDINAL) = 0, 2062, 3792, 48
_NET_WM_STRUT_PARTIAL(CARDINAL) = 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3838
_NET_WM_STRUT(CARDINAL) = 0, 0, 0, 0
[rave@mother ~]$ xprop | grep _WM_STRUT
_GNOME_WM_STRUT_AREA(CARDINAL) = 0, 200, 174, 1586
_NET_WM_STRUT_PARTIAL(CARDINAL) = 175, 0, 0, 0, 200, 1958, 0, 0, 0, 0, 0, 0
_NET_WM_STRUT(CARDINAL) = 175, 0, 0, 0
[rave@mother ~]$ 
```
So, problem isn't solved :/

**Comment by rbuj** [comment]
II'll debug it asap, but 2160 - 2062 = 98, and it seems to be obtained from the sum of the height of the top (50) and bottom panel (48).

**Comment by rbuj** [comment]
```diff
diff --git a/mate-panel/panel-toplevel.c b/mate-panel/panel-toplevel.c
index c6f19c0b..c214aaef 100644
--- a/mate-panel/panel-toplevel.c
+++ b/mate-panel/panel-toplevel.c
@@ -2514,7 +2514,7 @@ panel_toplevel_update_geometry (PanelToplevel  *toplevel,
 #ifdef HAVE_X11
        if (GDK_IS_X11_DISPLAY (gtk_widget_get_display (GTK_WIDGET (toplevel)))) {
                if (toplevel->priv->state == PANEL_STATE_NORMAL ||
-               toplevel->priv->state == PANEL_STATE_AUTO_HIDDEN) {
+               toplevel->priv->state != PANEL_STATE_AUTO_HIDDEN) {
                        panel_struts_update_toplevel_geometry (toplevel,
                                                        &toplevel->priv->geometry.x,
                                                        &toplevel->priv->geometry.y,
```

**Comment by raveit65** [comment]
xprop results are the same.
```
[rave@mother ~]$ xprop | grep _WM_STRUT
_GNOME_WM_STRUT_AREA(CARDINAL) = 0, 0, 3790, 50
_NET_WM_STRUT_PARTIAL(CARDINAL) = 0, 0, 51, 0, 0, 0, 0, 0, 0, 3838, 0, 0
_NET_WM_STRUT(CARDINAL) = 0, 0, 51, 0
[rave@mother ~]$ xprop | grep _WM_STRUT
_GNOME_WM_STRUT_AREA(CARDINAL) = 0, 2062, 3792, 48
_NET_WM_STRUT_PARTIAL(CARDINAL) = 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3838
_NET_WM_STRUT(CARDINAL) = 0, 0, 0, 0
[rave@mother ~]$ xprop | grep _WM_STRUT
_GNOME_WM_STRUT_AREA(CARDINAL) = 0, 200, 174, 1586
_NET_WM_STRUT_PARTIAL(CARDINAL) = 175, 0, 0, 0, 200, 1958, 0, 0, 0, 0, 0, 0
_NET_WM_STRUT(CARDINAL) = 175, 0, 0, 0
[rave@mother ~]$ 
```
But i see one third of a firefox search engine now after applying last patch, so you are on the right direction.
normal firefox window with search entry:
firefox_normal
firefox_maximized
As you can see one third of the firefox search engine is displayed now in maximize mode, before last patch the search engine was complete under the bottom panel.

**Comment by rbuj** [comment]
When hdpi is disabled it works as expected:
```
[robert@fedora ~]$ sh ./test.sh
_GNOME_WM_STRUT_AREA(CARDINAL) = 0, 0, 1920, 28
_NET_WM_STRUT_PARTIAL(CARDINAL) = 0, 0, 28, 0, 0, 0, 0, 0, 0, 1919, 0, 0
_NET_WM_STRUT(CARDINAL) = 0, 0, 28, 0
[robert@fedora ~]$ sh ./test.sh
_GNOME_WM_STRUT_AREA(CARDINAL) = 0, 1175, 1920, 25
_NET_WM_STRUT_PARTIAL(CARDINAL) = 0, 0, 0, 25, 0, 0, 0, 0, 0, 0, 0, 1919
_NET_WM_STRUT(CARDINAL) = 0, 0, 0, 25
[robert@fedora ~]$ sh ./test.sh
_GNOME_WM_STRUT_AREA(CARDINAL) = 0, 28, 25, 1147
_NET_WM_STRUT_PARTIAL(CARDINAL) = 25, 0, 0, 0, 28, 1174, 0, 0, 0, 0, 0, 0
_NET_WM_STRUT(CARDINAL) = 25, 0, 0, 0
```
And double click on window titlebar fits the entire window when hdpi is disabled:

Screenshot at 2021-12-18 23-34-39

So, it seems to be a problem about scaling...

**Comment by rbuj** [comment]
```
_GNOME_WM_STRUT_AREA(CARDINAL) = 0, 2062, 3792, 48
_NET_WM_STRUT_PARTIAL(CARDINAL) = 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3838
_NET_WM_STRUT(CARDINAL) = 0, 0, 0, 0
```
The first four values of `_NET_WM_STRUT_PARTIAL(CARDINAL)` are the same values of `_NET_WM_STRUT(CARDINAL)`, they are left, right, top, bottom, one of them should be non zero. it's the bottom panel because bottom_end_x is 3838, so missing X value, (X=bottom panel height).

```
_NET_WM_STRUT_PARTIAL(CARDINAL) = 0, 0, 0, X, 0, 0, 0, 0, 0, 0, 0, 3838
_NET_WM_STRUT(CARDINAL) = 0, 0, 0, X
```

ref: https://specifications.freedesktop.org/wm-spec/1.3/ar01s05.html

**Comment by rbuj** [comment]
I think the values are fine now (_NET_WM_STRUT, _NET_WM_STRUT_PARTIAL and _GNOME_WM_STRUT_AREA)

**Review by lukefromdc — APPROVED** [review]
This latest round of updates fixed my problems with windows maximizing under a right side panel when another monitor is to the right of the primary (on which that panel is set), and fixed the issue with two panels on the same edge as well. I could not find any problems with this build (12-19-2021 7:30AM EST) with a 4K primary monitor, a 1080p secondary monitor, and window-scaling-factor=2. Note that I have not tested monitors one above the other as I have never used that configuration, have no stands for setting up that way, and would have difficulty interacting with a mismatch of logical to physical monitor arrangements.

**Comment by raveit65** [comment]
> So, it seems to be a problem about scaling...

Indeed, issue was with a HIDPI setup of 2 Monitor in a vertical arrangement.
All fine without scaling:
panel-struts_2_monitors_vertical_without_hdipi
```
[rave@mother ~]$ xprop | grep _WM_STRUT
_GNOME_WM_STRUT_AREA(CARDINAL) = 0, 0, 1920, 27
_NET_WM_STRUT_PARTIAL(CARDINAL) = 0, 0, 27, 0, 0, 0, 0, 0, 0, 1919, 0, 0
_NET_WM_STRUT(CARDINAL) = 0, 0, 27, 0
[rave@mother ~]$ xprop | grep _WM_STRUT
_GNOME_WM_STRUT_AREA(CARDINAL) = 0, 0, 1920, 27
_NET_WM_STRUT_PARTIAL(CARDINAL) = 0, 0, 27, 0, 0, 0, 0, 0, 0, 1919, 0, 0
_NET_WM_STRUT(CARDINAL) = 0, 0, 27, 0
```
After latest changes it seems fine for HIDPI too.
panel-struts_2_monitors_vertical_with_hdipi
As you can see the firefox search engine is still there, and `xprops` results are looking good for top and bottom panel.
```
[rave@mother ~]$ xprop | grep _WM_STRUT
_GNOME_WM_STRUT_AREA(CARDINAL) = 0, 0, 3840, 54
_NET_WM_STRUT_PARTIAL(CARDINAL) = 0, 0, 54, 0, 0, 0, 0, 0, 0, 3838, 0, 0
_NET_WM_STRUT(CARDINAL) = 0, 0, 54, 0
[rave@mother ~]$ xprop | grep _WM_STRUT
_GNOME_WM_STRUT_AREA(CARDINAL) = 0, 2110, 3840, 50
_NET_WM_STRUT_PARTIAL(CARDINAL) = 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3838
_NET_WM_STRUT(CARDINAL) = 0, 0, 0, 0
```

**Review by raveit65 — APPROVED** [review]
LGTM,
no new build warnings and all mentioned reports seems to be fixed.

**Comment by raveit65** [comment]
@rbuj 
Thanks a lot, there is a nice bounty on this report.
https://github.com/mate-desktop/mate-panel/issues/803
https://www.bountysource.com/issues/57959471-panel-issues-in-dual-screen-layouts-overlapping-window-decoration-broken-hiding-behavior?show_profile_modal=1
You should claim it after this PR is merged.

**Pull request merged**
