### PR TITLE
Wayland support for the easy files

### PR DESCRIPTION
**Pull request by wmww**
This has a lot of the files that just need minor changes to support Wayland. It doesn't remove all X-specific code from the project and there is still no Wayland backend in place, so this should only be tested under X. If reviewers would like me to break this up into smaller pieces, just ask. Most of the commits are independent.

### CODE REVIEW

**Comment by wmww** [comment]
Nice, thanks.

This PR doesn't touch `mate-panel-applet-gsettings.h`, or any of the 6 files that include it. My previous PRs have touched some of the including files. FWIW I'm not getting those warnings on Ubuntu 18.10.

**Comment by raveit65** [comment]
Looks good in quick overview, but we're are going in freeze for 1.22 release today.
And i don't want to merge such a big change on the last day to avoid breaking the 1.22 release.
I hope 1.22 is released end of February and we can work again on it.
Thank you for your comprehension.

**Comment by wmww** [comment]
Bump. From what I can tell, the release has happened.

**Comment by raveit65** [comment]
> FWIW I'm not getting those warnings on Ubuntu 18.10.

You don't see that warning if gobject-introspection isn#t enabled.

**Pull request merged**
