### PR TITLE
GSettings key for icon sizes, change default menubar icon size to 22px + some fixes

### PR DESCRIPTION
**Pull request by XRevan86**
* Add a GSchema for changing icon size of menubar icon and menu item icons.
 * Default menubar icon is too big for a 24px panel as it touches the panel borders, so make it 22px.
 * Fix Gtk 3.16+ dishonouring mate-panel's defaults on menu icons size.
 * Also I cleaned code around icon loading a bit, fixed some warnings.

### CODE REVIEW

**Comment by Exalm** [comment]
Doesn't work on GTK2 build of 1.12.1. The patch applies cleanly, and it seems to lag less, but the lag is still noticeable. And the memory usage is actually higher with the patch (68mb instead of 53mb).

**Comment by raveit65** [comment]
Works great with MATE GTK+2 on fedora rawhide, nice feature :smiley: 
With MATE GTK+3.16 on fedora 22 changing menuitem size works great too,
only changing menubar icon size does not have any effect.
Not shure if this related to this PR.

....... great job
@monsta please test it too

**Comment by raveit65** [comment]
Ok, it works well in gtk3 too, now :)
@monsta 
i will merge it because i will make a 1.13.x release today.
We can always fix something in development phase.

**Comment by raveit65** [comment]
merged
https://github.com/mate-desktop/mate-panel/commit/bd3d7bc04d864d37e054b9e51fb48cbabb7e18f7
https://github.com/mate-desktop/mate-panel/commit/c29a88ff648af2e07a7cd657c027f1e5bf665ed6
https://github.com/mate-desktop/mate-panel/commit/22c04b86a42678e8099d1af00cb156c227ea669d
https://github.com/mate-desktop/mate-panel/commit/a0a59122dab148294f199aeb8e9a85901793c435
https://github.com/mate-desktop/mate-panel/commit/44a6c2f7e478fce00cc987bb76ac519704c13da2

Thanks a lot :)

**Pull request closed without merging**
